//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACT.SpecialSpellTimer.resources.strings {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings_JP {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_JP() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ACT.SpecialSpellTimer.resources.strings.Strings-JP", typeof(Strings_JP).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   巴術士과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ACN {
            get {
                return ResourceManager.GetString("ACN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ACT.SpecialSpellTimer Assemblyの解決で例外が発生しました。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ACTAssemblyError {
            get {
                return ResourceManager.GetString("ACTAssemblyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アクション과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ActionHeader {
            get {
                return ResourceManager.GetString("ActionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アクター과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ActorHeader {
            get {
                return ResourceManager.GetString("ActorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ACT.SpecialSpellTimer プラグインの初期化で例外が発生しました。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ACTPluginStartError {
            get {
                return ResourceManager.GetString("ACTPluginStartError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ACT.SpecialSpellTimer プラグインの終了で例外が発生しました。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ACTPluginStopError {
            get {
                return ResourceManager.GetString("ACTPluginStopError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   追加과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   継続的にマッチさせてメッセージを追加表示する과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AddMessageCheckBox {
            get {
                return ResourceManager.GetString("AddMessageCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アラーム及びTTS과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AlarmTab {
            get {
                return ResourceManager.GetString("AlarmTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   錬金術師과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ALC {
            get {
                return ResourceManager.GetString("ALC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全てOFF과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AllOffButton {
            get {
                return ResourceManager.GetString("AllOffButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全てON과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AllOnButton {
            get {
                return ResourceManager.GetString("AllOnButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テロップを常に表示する과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AlwaysDisplayTelop {
            get {
                return ResourceManager.GetString("AlwaysDisplayTelop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   分析する과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AnalyzeCombat {
            get {
                return ResourceManager.GetString("AnalyzeCombat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   適用する과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ApplyButton {
            get {
                return ResourceManager.GetString("ApplyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   弓術士과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ARC {
            get {
                return ResourceManager.GetString("ARC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   甲冑師과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ARM {
            get {
                return ResourceManager.GetString("ARM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   占星術師과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AST {
            get {
                return ResourceManager.GetString("AST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;AST&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ASTLabel {
            get {
                return ResourceManager.GetString("ASTLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   逆(遠い順)にする과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AutoSortReverseCheckbox {
            get {
                return ResourceManager.GetString("AutoSortReverseCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   背景色のアルファチャンネル과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BackgroundColorAlphaTitle {
            get {
                return ResourceManager.GetString("BackgroundColorAlphaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ﾊﾞｰのｻｲｽﾞ과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BarSize {
            get {
                return ResourceManager.GetString("BarSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   黒魔道士과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BLM {
            get {
                return ResourceManager.GetString("BLM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;BLM&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BLMLabel {
            get {
                return ResourceManager.GetString("BLMLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   園芸師과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BOT {
            get {
                return ResourceManager.GetString("BOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   吟遊詩人과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BRD {
            get {
                return ResourceManager.GetString("BRD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;BRD&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BRDLabel {
            get {
                return ResourceManager.GetString("BRDLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   鍛冶師과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BSM {
            get {
                return ResourceManager.GetString("BSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バッファのサイズ과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BufferSize {
            get {
                return ResourceManager.GetString("BufferSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャンセル과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   背景色のアルファチャンネルを変更する과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ChangeBackgroundAlpha {
            get {
                return ResourceManager.GetString("ChangeBackgroundAlpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   背景色を変更する과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ChangeBackgroundColor {
            get {
                return ResourceManager.GetString("ChangeBackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バーの色を変更する과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ChangeBarColor {
            get {
                return ResourceManager.GetString("ChangeBarColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バーのアウトラインの色を変更する과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ChangeBarOutlineColor {
            get {
                return ResourceManager.GetString("ChangeBarOutlineColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ※右クリックで変更과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ChangeByRightClicking {
            get {
                return ResourceManager.GetString("ChangeByRightClicking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォントを変更する과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ChangeFont {
            get {
                return ResourceManager.GetString("ChangeFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォントの色を変更する과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ChangeFontColor {
            get {
                return ResourceManager.GetString("ChangeFontColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォントのアウトラインの色を変更する과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ChangeFontOutlineColor {
            get {
                return ResourceManager.GetString("ChangeFontOutlineColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全て削除과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ClearAllButton {
            get {
                return ResourceManager.GetString("ClearAllButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クリックスルー과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ClickThrough {
            get {
                return ResourceManager.GetString("ClickThrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   幻術士과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CNJ {
            get {
                return ResourceManager.GetString("CNJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   戦闘アナライザ과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CombatAnalyzerTabTitle {
            get {
                return ResourceManager.GetString("CombatAnalyzerTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログを解析しています . . .과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CombatAnalyzing {
            get {
                return ResourceManager.GetString("CombatAnalyzing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   分析用に敵の行動を記録する과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CombatLogEnabledCheckBox {
            get {
                return ResourceManager.GetString("CombatLogEnabledCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   「, (カンマ)」で改行になります과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CommaLineBreakExplain {
            get {
                return ResourceManager.GetString("CommaLineBreakExplain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログをコピーする과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CopyLog {
            get {
                return ResourceManager.GetString("CopyLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログの詳細をコピーする과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CopyLogDetail {
            get {
                return ResourceManager.GetString("CopyLogDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   木工師과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CRP {
            get {
                return ResourceManager.GetString("CRP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   調理師과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CUL {
            get {
                return ResourceManager.GetString("CUL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ディレイ後に鳴らすサウンド과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DelayedSoundEffect {
            get {
                return ResourceManager.GetString("DelayedSoundEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログにマッチしてｎ秒後に鳴らすサウンド과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DelayedSoundEffectAfterMatch {
            get {
                return ResourceManager.GetString("DelayedSoundEffectAfterMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FCから始まるPacketDumpも解析対象にする과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DetectPacketDumpLabel {
            get {
                return ResourceManager.GetString("DetectPacketDumpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ※0にすると無効（消去しない）과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DisableWhenClear {
            get {
                return ResourceManager.GetString("DisableWhenClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表示順과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DisplayOrderLabel {
            get {
                return ResourceManager.GetString("DisplayOrderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   残り時間をプログレスバーで表示する과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DisplayRemainingTimeCheckBox {
            get {
                return ResourceManager.GetString("DisplayRemainingTimeCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   秒間表示する과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DisplaySeconds {
            get {
                return ResourceManager.GetString("DisplaySeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リキャスト後に消去しない과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DontHideCheckBox {
            get {
                return ResourceManager.GetString("DontHideCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ダウンロードしますか？과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DownloadPrompt {
            get {
                return ResourceManager.GetString("DownloadPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DQX向け機能を有効にする과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DQXOptionEnabledCheckBox {
            get {
                return ResourceManager.GetString("DQXOptionEnabledCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DQX向けオプション과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DQXOptionTabPage {
            get {
                return ResourceManager.GetString("DQXOptionTabPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;me&gt; : プレイヤー名(パーティメンバ1)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DQXPlayerNameLabel {
            get {
                return ResourceManager.GetString("DQXPlayerNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;2&gt; : パーティメンバ2과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DQXPTMember2Label {
            get {
                return ResourceManager.GetString("DQXPTMember2Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;3&gt; : パーティメンバ3과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DQXPTMember3Label {
            get {
                return ResourceManager.GetString("DQXPTMember3Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;4&gt; : パーティメンバ4과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DQXPTMember4Label {
            get {
                return ResourceManager.GetString("DQXPTMember4Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;5&gt; : パーティメンバ5과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DQXPTMember5Label {
            get {
                return ResourceManager.GetString("DQXPTMember5Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;6&gt; : パーティメンバ6과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DQXPTMember6Label {
            get {
                return ResourceManager.GetString("DQXPTMember6Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;7&gt; : パーティメンバ7과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DQXPTMember7Label {
            get {
                return ResourceManager.GetString("DQXPTMember7Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;8&gt; : パーティメンバ8과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DQXPTMember8Label {
            get {
                return ResourceManager.GetString("DQXPTMember8Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   竜騎士과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DRG {
            get {
                return ResourceManager.GetString("DRG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;DRG&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DRGLabel {
            get {
                return ResourceManager.GetString("DRGLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   暗黒騎士과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DRK {
            get {
                return ResourceManager.GetString("DRK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;DRK&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DRKLabel {
            get {
                return ResourceManager.GetString("DRKLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   秒後から과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   経過秒과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ElapsedHeader {
            get {
                return ResourceManager.GetString("ElapsedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   有効과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   有効과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string EnabledSpellTimerNoDecimalCheckBox {
            get {
                return ResourceManager.GetString("EnabledSpellTimerNoDecimalCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リキャスト完了後に消去する과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string EraseAfterRecast {
            get {
                return ResourceManager.GetString("EraseAfterRecast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ExportButton {
            get {
                return ResourceManager.GetString("ExportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CSV保存과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ExportCSVButton {
            get {
                return ResourceManager.GetString("ExportCSVButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   元のリキャストタイムを超えて延長する과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ExtendBeyondOriginalRecastTimeCheckBox {
            get {
                return ResourceManager.GetString("ExtendBeyondOriginalRecastTimeCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   秒を上限とする과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ExtendLimitLabel {
            get {
                return ResourceManager.GetString("ExtendLimitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スペル位置を固定する과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FixedPositionSpell {
            get {
                return ResourceManager.GetString("FixedPositionSpell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   漁師과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FSH {
            get {
                return ResourceManager.GetString("FSH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全般과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GeneralTab {
            get {
                return ResourceManager.GetString("GeneralTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   剣術士과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GLD {
            get {
                return ResourceManager.GetString("GLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   彫金師과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GSM {
            get {
                return ResourceManager.GetString("GSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スペル名を表示しない과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HideSpellNameCheckBox {
            get {
                return ResourceManager.GetString("HideSpellNameCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   非アクティブのときオーバーレイを隠す과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HideWhenNotActiceCheckBox {
            get {
                return ResourceManager.GetString("HideWhenNotActiceCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   水平レイアウト과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HorizontalLayout {
            get {
                return ResourceManager.GetString("HorizontalLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HP과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HPHeader {
            get {
                return ResourceManager.GetString("HPHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログにマッチした直後に鳴らすサウンド과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ImmediateSoundEffect {
            get {
                return ResourceManager.GetString("ImmediateSoundEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ImportButton {
            get {
                return ResourceManager.GetString("ImportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   初期化과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InitializationButton {
            get {
                return ResourceManager.GetString("InitializationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   稼働中과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string IsRunning {
            get {
                return ResourceManager.GetString("IsRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   停止中과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string IsStopping {
            get {
                return ResourceManager.GetString("IsStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   言語 (Language)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Combat Log Analyze과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string lblCombatAnalyzer {
            get {
                return ResourceManager.GetString("lblCombatAnalyzer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Party Member Alarm과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string lblDQX {
            get {
                return ResourceManager.GetString("lblDQX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language Setting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string lblLanguage {
            get {
                return ResourceManager.GetString("lblLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Monitor과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string lblMonitor {
            get {
                return ResourceManager.GetString("lblMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Spell Timer Setting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string lblSpellTimer {
            get {
                return ResourceManager.GetString("lblSpellTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   行과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LinesLabel {
            get {
                return ResourceManager.GetString("LinesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スペシャルスペルタイマ(スペスペ)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LN_Tabname {
            get {
                return ResourceManager.GetString("LN_Tabname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   槍術士과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LNC {
            get {
                return ResourceManager.GetString("LNC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配色を読み込む과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LoadColorSet {
            get {
                return ResourceManager.GetString("LoadColorSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XMLファイルの読み込みで例外が発生しました과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LoadXMLError {
            get {
                return ResourceManager.GetString("LoadXMLError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   位置과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログ과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LogHeader {
            get {
                return ResourceManager.GetString("LogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Log과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LogLabel {
            get {
                return ResourceManager.GetString("LogLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログ処理の最短間隔과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LogPollSleepIntervalLabel {
            get {
                return ResourceManager.GetString("LogPollSleepIntervalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Log과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LogTabPage {
            get {
                return ResourceManager.GetString("LogTabPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   種類과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LogTypeHeader {
            get {
                return ResourceManager.GetString("LogTypeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   革細工師과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LTW {
            get {
                return ResourceManager.GetString("LTW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マージン과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Margin {
            get {
                return ResourceManager.GetString("Margin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログに対して部分一致でマッチングします\n例)\nマッチングワード : は「凍てつく剣」の構え\nログ : シヴァは「凍てつく剣」の構え。\n→ マッチします과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MatchingKeywordExplanationTooltip {
            get {
                return ResourceManager.GetString("MatchingKeywordExplanationTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログに対するマッチングワード과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MatchingLogWordLabel {
            get {
                return ResourceManager.GetString("MatchingLogWordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   延長するマッチングワード과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MatchingLogWordToExpandLabel {
            get {
                return ResourceManager.GetString("MatchingLogWordToExpandLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   非表示にするマッチングワード과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MatchingWordsToHide {
            get {
                return ResourceManager.GetString("MatchingWordsToHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログにマッチして・・・과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MatchLogLabel {
            get {
                return ResourceManager.GetString("MatchLogLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   機工士과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MCH {
            get {
                return ResourceManager.GetString("MCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;MCH&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MCHLabel {
            get {
                return ResourceManager.GetString("MCHLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;me&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MeLabel {
            get {
                return ResourceManager.GetString("MeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;2&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Member2Label {
            get {
                return ResourceManager.GetString("Member2Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;3&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Member3Label {
            get {
                return ResourceManager.GetString("Member3Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;4&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Member4Label {
            get {
                return ResourceManager.GetString("Member4Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;5&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Member5Label {
            get {
                return ResourceManager.GetString("Member5Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;6&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Member6Label {
            get {
                return ResourceManager.GetString("Member6Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;7&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Member7Label {
            get {
                return ResourceManager.GetString("Member7Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;8&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Member8Label {
            get {
                return ResourceManager.GetString("Member8Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テロップに表示するメッセージ과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MessageOnTickerLabel {
            get {
                return ResourceManager.GetString("MessageOnTickerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ミリ秒과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Millisecond {
            get {
                return ResourceManager.GetString("Millisecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   採掘師과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MIN {
            get {
                return ResourceManager.GetString("MIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   モンク과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MNK {
            get {
                return ResourceManager.GetString("MNK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;MNK&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MNKLabel {
            get {
                return ResourceManager.GetString("MNKLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   モニター과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MonitorTabPage {
            get {
                return ResourceManager.GetString("MonitorTabPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   斧術士과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MRD {
            get {
                return ResourceManager.GetString("MRD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Telop과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NewTelop {
            get {
                return ResourceManager.GetString("NewTelop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アップデートの確認で例外が発生しました。{0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NewVersionError {
            get {
                return ResourceManager.GetString("NewVersionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} の新しいバージョンがリリースされています。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NewVersionReleased {
            get {
                return ResourceManager.GetString("NewVersionReleased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   忍者과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NIN {
            get {
                return ResourceManager.GetString("NIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;NIN&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NINLabel {
            get {
                return ResourceManager.GetString("NINLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string No1Label {
            get {
                return ResourceManager.GetString("No1Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string No2Label {
            get {
                return ResourceManager.GetString("No2Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ※ログマッチ時に標準のスペルタイマーへの通知が行われます（試験的な機能）과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NotifyNormalSpellTimerExplainLabel {
            get {
                return ResourceManager.GetString("NotifyNormalSpellTimerExplainLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   標準のスペルタイマーに通知する과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NotifyNormalSpellTimerLabel {
            get {
                return ResourceManager.GetString("NotifyNormalSpellTimerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NumberHeader {
            get {
                return ResourceManager.GetString("NumberHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OKButton {
            get {
                return ResourceManager.GetString("OKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   0:透明, 255:不透明과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OpacityDescription {
            get {
                return ResourceManager.GetString("OpacityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   オプション과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OptionTabPageTitle {
            get {
                return ResourceManager.GetString("OptionTabPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リキャストタイムを重ねる과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OverlapRecastTimeCheckBox {
            get {
                return ResourceManager.GetString("OverlapRecastTimeCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   オーバーレイの表示スイッチ\n現在の状態 -&gt; OFF과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OverlayDisplaySwitchIsOff {
            get {
                return ResourceManager.GetString("OverlayDisplaySwitchIsOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   オーバーレイの表示スイッチ\n現在の状態 -&gt; ON과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OverlayDisplaySwitchIsOn {
            get {
                return ResourceManager.GetString("OverlayDisplaySwitchIsOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FFXIVが起動していなくてもオーバーレイを表示する과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OverlayForceVisibleCheckBox {
            get {
                return ResourceManager.GetString("OverlayForceVisibleCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スペルタイマが完了した時のテキスト(Over)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OverTextLabel {
            get {
                return ResourceManager.GetString("OverTextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表示するパネルの名前과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PanelNameLabel {
            get {
                return ResourceManager.GetString("PanelNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ※&lt;2&gt;～&lt;8&gt;が使用可能になります。ただし2～8の順序は正しくない場合があります。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PartyMemberNumberExplainLabel {
            get {
                return ResourceManager.GetString("PartyMemberNumberExplainLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PTメンバの代名詞を有効にする과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PartyPronounLabel {
            get {
                return ResourceManager.GetString("PartyPronounLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ♪과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PlayButton {
            get {
                return ResourceManager.GetString("PlayButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ナイト과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PLD {
            get {
                return ResourceManager.GetString("PLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;PLD&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PLDLabel {
            get {
                return ResourceManager.GetString("PLDLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please Wait과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PleaseWait1 {
            get {
                return ResourceManager.GetString("PleaseWait1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please Wait .과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PleaseWait2 {
            get {
                return ResourceManager.GetString("PleaseWait2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please Wait . .과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PleaseWait3 {
            get {
                return ResourceManager.GetString("PleaseWait3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please Wait . . .과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PleaseWait4 {
            get {
                return ResourceManager.GetString("PleaseWait4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please Wait . . . .과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PleaseWait5 {
            get {
                return ResourceManager.GetString("PleaseWait5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ※より小さいほうが優先과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PriorityExplainLabel {
            get {
                return ResourceManager.GetString("PriorityExplainLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プログレスバーの見た目과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ProgressBarAppearance {
            get {
                return ResourceManager.GetString("ProgressBarAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   格闘士과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PUG {
            get {
                return ResourceManager.GetString("PUG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スペルタイマが完了した時のテキスト(Ready)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReadyTextLabel {
            get {
                return ResourceManager.GetString("ReadyTextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リキャスト完了時に鳴らすサウンド과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RecastCompleteSoundEffect {
            get {
                return ResourceManager.GetString("RecastCompleteSoundEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スペルのリキャスト時間(秒)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RecastTimeLabel {
            get {
                return ResourceManager.GetString("RecastTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アイコン暗転時の明るさ과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReduceIconBrightness {
            get {
                return ResourceManager.GetString("ReduceIconBrightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リキャスト中はアイコンを暗くする과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReduceIconBrightnessCheckBox {
            get {
                return ResourceManager.GetString("ReduceIconBrightnessCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReferenceButton {
            get {
                return ResourceManager.GetString("ReferenceButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正規表現が無効でも部分一致は既定で有効となっています\n正規表現OFFでの部分一致のほうがパフォーマンスは向上します과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RegularExpressionExplanationTooltip {
            get {
                return ResourceManager.GetString("RegularExpressionExplanationTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ツールチップ記号を除去する과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RemoveTooltipSymbolsLabel {
            get {
                return ResourceManager.GetString("RemoveTooltipSymbolsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リキャスト後に繰り返す과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RepeatCheckBox {
            get {
                return ResourceManager.GetString("RepeatCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ※再起動が必要과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RequiresRestart {
            get {
                return ResourceManager.GetString("RequiresRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   あなたはすべての設定とテロップ位置をリセットしてもよろしいですか？과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ResetAllPrompt {
            get {
                return ResourceManager.GetString("ResetAllPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全滅時にカウントをリセットする과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ResetOnWipeOutLabel {
            get {
                return ResourceManager.GetString("ResetOnWipeOutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スペルをこのバーサイズで統一する과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ResetSpellBarSize {
            get {
                return ResourceManager.GetString("ResetSpellBarSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スペルをこの配色で統一する과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ResetSpellColor {
            get {
                return ResourceManager.GetString("ResetSpellColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スペルをこのフォントで統一する과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ResetSpellFont {
            get {
                return ResourceManager.GetString("ResetSpellFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テロップをこの配色で統一する과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ResetTelopColor {
            get {
                return ResourceManager.GetString("ResetTelopColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テロップをこのフォントで統一する과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ResetTelopFont {
            get {
                return ResourceManager.GetString("ResetTelopFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   進行方向を逆にする과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReverseDirectionCheckbox {
            get {
                return ResourceManager.GetString("ReverseDirectionCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   双剣士과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ROG {
            get {
                return ResourceManager.GetString("ROG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サンプルスペル과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SampleSpell {
            get {
                return ResourceManager.GetString("SampleSpell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サンプルテロップ과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SampleTelop {
            get {
                return ResourceManager.GetString("SampleTelop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配色を保存する과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SaveColorSet {
            get {
                return ResourceManager.GetString("SaveColorSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログを保存する과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SaveLogLabel {
            get {
                return ResourceManager.GetString("SaveLogLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   学者과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SCH {
            get {
                return ResourceManager.GetString("SCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;SCH&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SCHLabel {
            get {
                return ResourceManager.GetString("SCHLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画面の更新間隔과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ScreenUpdateTimeLabel {
            get {
                return ResourceManager.GetString("ScreenUpdateTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   秒延長する과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SecondsLabel {
            get {
                return ResourceManager.GetString("SecondsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   秒後과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SecondsLater {
            get {
                return ResourceManager.GetString("SecondsLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全て選択과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ジョブを限定する과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SelectJobButton {
            get {
                return ResourceManager.GetString("SelectJobButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ※対象とするジョブを限定したい場合はチェックをONにしてください과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SelectJobSubtitle {
            get {
                return ResourceManager.GetString("SelectJobSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象のジョブを選択してください과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SelectJobTitle {
            get {
                return ResourceManager.GetString("SelectJobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ゾーンを限定する과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SelectZoneButton {
            get {
                return ResourceManager.GetString("SelectZoneButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象のゾーンを選択して下さい과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SelectZoneTitle {
            get {
                return ResourceManager.GetString("SelectZoneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   開始条件を設定する과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SetConditionForStartButton {
            get {
                return ResourceManager.GetString("SetConditionForStartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   条件を設定して下さい과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SetConditionTitle {
            get {
                return ResourceManager.GetString("SetConditionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このログを経過秒の起点にする과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SetLogOrigin {
            get {
                return ResourceManager.GetString("SetLogOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スペルリストに表示する과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ShowProgressBarCheckBox {
            get {
                return ResourceManager.GetString("ShowProgressBarCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正規表現を単純にする과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SimpleRegexLabel {
            get {
                return ResourceManager.GetString("SimpleRegexLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   召喚士과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SMN {
            get {
                return ResourceManager.GetString("SMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;SMN&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SMNLabel {
            get {
                return ResourceManager.GetString("SMNLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リキャスト完了が近い順でソートする과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SortByRecastOrder {
            get {
                return ResourceManager.GetString("SortByRecastOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リキャスト完了ｎ秒前に鳴らすサウンド과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SoundEffectBeforeComplete {
            get {
                return ResourceManager.GetString("SoundEffectBeforeComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ACT.SpecialSpellTimer Soundの再生で例外が発生しました。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SoundError {
            get {
                return ResourceManager.GetString("SoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   秒後に鳴らす과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SoundInSeconds {
            get {
                return ResourceManager.GetString("SoundInSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   秒前に鳴らす과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SoundInSecondsBefore {
            get {
                return ResourceManager.GetString("SoundInSecondsBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   周期과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SpanHeader {
            get {
                return ResourceManager.GetString("SpanHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ▶과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SpeakButton {
            get {
                return ResourceManager.GetString("SpeakButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ※スペックに合わせて設定してください과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SpecsLabel {
            get {
                return ResourceManager.GetString("SpecsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全てのスペルを削除してよろしいですか？과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SpellClearAllPrompt {
            get {
                return ResourceManager.GetString("SpellClearAllPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スペルのアイコン과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SpellIconLabel {
            get {
                return ResourceManager.GetString("SpellIconLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スペルアイコンのサイズ과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SpellIconSizeLabel {
            get {
                return ResourceManager.GetString("SpellIconSizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スペルの名前과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SpellNameLabel {
            get {
                return ResourceManager.GetString("SpellNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ※描画の負荷が下がります（要再起動）과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SpellTimerFormatExplainLabel {
            get {
                return ResourceManager.GetString("SpellTimerFormatExplainLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スペルタイマの秒数を整数表示にする과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SpellTimerFormatLabel {
            get {
                return ResourceManager.GetString("SpellTimerFormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ACT.SpecialSpellTimer スペルタイマWindowのRefreshで例外が発生しました。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SpellTimerRefreshError {
            get {
                return ResourceManager.GetString("SpellTimerRefreshError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スペシャルスペルタイマ과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SpellTimerTabTitle {
            get {
                return ResourceManager.GetString("SpellTimerTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スペスペ과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SupeSupe {
            get {
                return ResourceManager.GetString("SupeSupe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スペルを表示する과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SwitchOverlayButton {
            get {
                return ResourceManager.GetString("SwitchOverlayButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Detail Options과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string tabDetailOptions {
            get {
                return ResourceManager.GetString("tabDetailOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Overlay Options과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string tabOverlayOptions {
            get {
                return ResourceManager.GetString("tabOverlayOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add New과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TelopAddButton {
            get {
                return ResourceManager.GetString("TelopAddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear All과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TelopClearAllButton {
            get {
                return ResourceManager.GetString("TelopClearAllButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全てのテロップを削除してよろしいですか？과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TelopClearAllPrompt {
            get {
                return ResourceManager.GetString("TelopClearAllPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テロップの表示スイッチ\n現在の状態 -&gt; 通常과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TelopDisplaySwitchIsOff {
            get {
                return ResourceManager.GetString("TelopDisplaySwitchIsOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テロップの表示スイッチ\n現在の状態 -&gt; 常に表示(位置調整向け)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TelopDisplaySwitchIsOn {
            get {
                return ResourceManager.GetString("TelopDisplaySwitchIsOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TelopExportButton {
            get {
                return ResourceManager.GetString("TelopExportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TelopImportButton {
            get {
                return ResourceManager.GetString("TelopImportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {COUNT}と記入するとテロップが消えるまでの秒数に置換されます\n{COUNT} → 小数点第1位まで表示。例) 30.0\n{COUNT0} → 整数部のみ表示。例) 30과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TelopMessageExplanationTooltip {
            get {
                return ResourceManager.GetString("TelopMessageExplanationTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ワンポイントテロップ과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TelopTabPageTitle {
            get {
                return ResourceManager.GetString("TelopTabPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TextToSpeak과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TextToSpeakLabel {
            get {
                return ResourceManager.GetString("TextToSpeakLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   呪術士과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string THM {
            get {
                return ResourceManager.GetString("THM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テロップの名前과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TickerName {
            get {
                return ResourceManager.GetString("TickerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タイムスタンプ과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TimestampHeader {
            get {
                return ResourceManager.GetString("TimestampHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スペルの名前(表示テキスト)が異なる場合にインスタンス化する과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ToInstanceCheckBox {
            get {
                return ResourceManager.GetString("ToInstanceCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   オーバーレイの透過率과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TransmitOverlay {
            get {
                return ResourceManager.GetString("TransmitOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UpdateButton {
            get {
                return ResourceManager.GetString("UpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スペル名を入力してください과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UpdateSpellNameTitle {
            get {
                return ResourceManager.GetString("UpdateSpellNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パネル名を入力してください과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UpdateSpellPanelTitle {
            get {
                return ResourceManager.GetString("UpdateSpellPanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テロップの名前を入力してください과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UpdateTelopNameTitle {
            get {
                return ResourceManager.GetString("UpdateTelopNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FFXIV以外で使用する과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UseOtherThanFFXIVCheckbox {
            get {
                return ResourceManager.GetString("UseOtherThanFFXIVCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正規表現ON과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UseRegex {
            get {
                return ResourceManager.GetString("UseRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   戦士과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WAR {
            get {
                return ResourceManager.GetString("WAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;WAR&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WARLabel {
            get {
                return ResourceManager.GetString("WARLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ACT.SpecialSpellTimer フォアグラウンドWindowの監視で例外が発生しました。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WatchActiveError {
            get {
                return ResourceManager.GetString("WatchActiveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   wave과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WaveSoundLabel {
            get {
                return ResourceManager.GetString("WaveSoundLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   白魔道士과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WHM {
            get {
                return ResourceManager.GetString("WHM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;WHM&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WHMLabel {
            get {
                return ResourceManager.GetString("WHMLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   裁縫師과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WVR {
            get {
                return ResourceManager.GetString("WVR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   X과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string X {
            get {
                return ResourceManager.GetString("X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XMLファイル (*.xml)|*.xml|全てのファイル (*.*)|*.*과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string XmlFileFilter {
            get {
                return ResourceManager.GetString("XmlFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Y과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Y {
            get {
                return ResourceManager.GetString("Y", resourceCulture);
            }
        }
    }
}
