//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACT.SpecialSpellTimer.resources.strings {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings_KR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_KR() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ACT.SpecialSpellTimer.resources.strings.Strings-KR", typeof(Strings_KR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   비술사과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ACN {
            get {
                return ResourceManager.GetString("ACN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   스페셜 스펠 타이머에 어셈블리 예외가 발생했습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ACTAssemblyError {
            get {
                return ResourceManager.GetString("ACTAssemblyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   동작과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ActionHeader {
            get {
                return ResourceManager.GetString("ActionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시전자과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ActorHeader {
            get {
                return ResourceManager.GetString("ActorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   스페셜 스펠 타이머에 초기화 예외가 발생했습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ACTPluginStartError {
            get {
                return ResourceManager.GetString("ACTPluginStartError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   스페셜 스펠 타이머에 종료 예외가 발생했습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ACTPluginStopError {
            get {
                return ResourceManager.GetString("ACTPluginStopError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   추가과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   타이머 추가시 재시작과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AddMessageCheckBox {
            get {
                return ResourceManager.GetString("AddMessageCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   알림 또는 TTS (글자 읽어주기 보조도구)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AlarmTab {
            get {
                return ResourceManager.GetString("AlarmTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   연금술사과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ALC {
            get {
                return ResourceManager.GetString("ALC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   모두 끄기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AllOffButton {
            get {
                return ResourceManager.GetString("AllOffButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   모두 켜기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AllOnButton {
            get {
                return ResourceManager.GetString("AllOnButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   항상 위과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AlwaysDisplayTelop {
            get {
                return ResourceManager.GetString("AlwaysDisplayTelop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   분석과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AnalyzeCombat {
            get {
                return ResourceManager.GetString("AnalyzeCombat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   확인과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ApplyButton {
            get {
                return ResourceManager.GetString("ApplyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   궁술사과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ARC {
            get {
                return ResourceManager.GetString("ARC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   갑주제작사과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ARM {
            get {
                return ResourceManager.GetString("ARM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   점성술사과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AST {
            get {
                return ResourceManager.GetString("AST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;AST&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ASTLabel {
            get {
                return ResourceManager.GetString("ASTLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   역순 정렬과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AutoSortReverseCheckbox {
            get {
                return ResourceManager.GetString("AutoSortReverseCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   배경색 알파 채널(투명도)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BackgroundColorAlphaTitle {
            get {
                return ResourceManager.GetString("BackgroundColorAlphaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   막대 크기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BarSize {
            get {
                return ResourceManager.GetString("BarSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   흑마도사과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BLM {
            get {
                return ResourceManager.GetString("BLM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;BLM&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BLMLabel {
            get {
                return ResourceManager.GetString("BLMLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   원예가과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BOT {
            get {
                return ResourceManager.GetString("BOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   음유시인과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BRD {
            get {
                return ResourceManager.GetString("BRD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;BRD&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BRDLabel {
            get {
                return ResourceManager.GetString("BRDLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   대장장이과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BSM {
            get {
                return ResourceManager.GetString("BSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   버퍼 사이즈과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BufferSize {
            get {
                return ResourceManager.GetString("BufferSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   취소과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   배경 투명도과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ChangeBackgroundAlpha {
            get {
                return ResourceManager.GetString("ChangeBackgroundAlpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   배경 색상과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ChangeBackgroundColor {
            get {
                return ResourceManager.GetString("ChangeBackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   막대 색상과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ChangeBarColor {
            get {
                return ResourceManager.GetString("ChangeBarColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   막대 테두리 색상과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ChangeBarOutlineColor {
            get {
                return ResourceManager.GetString("ChangeBarOutlineColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   오른쪽 클릭으로 수정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ChangeByRightClicking {
            get {
                return ResourceManager.GetString("ChangeByRightClicking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   글씨체과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ChangeFont {
            get {
                return ResourceManager.GetString("ChangeFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   글자 색상과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ChangeFontColor {
            get {
                return ResourceManager.GetString("ChangeFontColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   글자 테두리 색상과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ChangeFontOutlineColor {
            get {
                return ResourceManager.GetString("ChangeFontOutlineColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   모두 삭제과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ClearAllButton {
            get {
                return ResourceManager.GetString("ClearAllButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   클릭 통과과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ClickThrough {
            get {
                return ResourceManager.GetString("ClickThrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   환술사과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CNJ {
            get {
                return ResourceManager.GetString("CNJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   전투 분석과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CombatAnalyzerTabTitle {
            get {
                return ResourceManager.GetString("CombatAnalyzerTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   로그를 분석 중입니다...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CombatAnalyzing {
            get {
                return ResourceManager.GetString("CombatAnalyzing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   전투 로그 분석 활성화과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CombatLogEnabledCheckBox {
            get {
                return ResourceManager.GetString("CombatLogEnabledCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   콤마 &quot;,&quot;로 줄 변경과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CommaLineBreakExplain {
            get {
                return ResourceManager.GetString("CommaLineBreakExplain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   로그 복사과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CopyLog {
            get {
                return ResourceManager.GetString("CopyLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   상세 로그 복사과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CopyLogDetail {
            get {
                return ResourceManager.GetString("CopyLogDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   목수과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CRP {
            get {
                return ResourceManager.GetString("CRP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   요리사과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CUL {
            get {
                return ResourceManager.GetString("CUL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   소리 재생 지연과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DelayedSoundEffect {
            get {
                return ResourceManager.GetString("DelayedSoundEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   로그 일치 시 N초 후 소리 재생과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DelayedSoundEffectAfterMatch {
            get {
                return ResourceManager.GetString("DelayedSoundEffectAfterMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   삭제과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ※ 비활성 하려면 0으로 설정 (숨겨지지 않음)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DisableWhenClear {
            get {
                return ResourceManager.GetString("DisableWhenClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   우선 순위과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DisplayOrderLabel {
            get {
                return ResourceManager.GetString("DisplayOrderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   진행 막대 표시과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DisplayRemainingTimeCheckBox {
            get {
                return ResourceManager.GetString("DisplayRemainingTimeCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   초과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DisplaySeconds {
            get {
                return ResourceManager.GetString("DisplaySeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   항상 표시 (완료 시)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DontHideCheckBox {
            get {
                return ResourceManager.GetString("DontHideCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   다운로드를 원하십니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DownloadPrompt {
            get {
                return ResourceManager.GetString("DownloadPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DQX 기능 활성화과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DQXOptionEnabledCheckBox {
            get {
                return ResourceManager.GetString("DQXOptionEnabledCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DQX 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DQXOptionTabPage {
            get {
                return ResourceManager.GetString("DQXOptionTabPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;me&gt; : 자신과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DQXPlayerNameLabel {
            get {
                return ResourceManager.GetString("DQXPlayerNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;2&gt; : 파티원 2과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DQXPTMember2Label {
            get {
                return ResourceManager.GetString("DQXPTMember2Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;3&gt; : 파티원 3과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DQXPTMember3Label {
            get {
                return ResourceManager.GetString("DQXPTMember3Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;4&gt; : 파티원 4과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DQXPTMember4Label {
            get {
                return ResourceManager.GetString("DQXPTMember4Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;5&gt; : 파티원 5과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DQXPTMember5Label {
            get {
                return ResourceManager.GetString("DQXPTMember5Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;6&gt; : 파티원 6과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DQXPTMember6Label {
            get {
                return ResourceManager.GetString("DQXPTMember6Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;7&gt; : 파티원 7과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DQXPTMember7Label {
            get {
                return ResourceManager.GetString("DQXPTMember7Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;8&gt; : 파티원 8과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DQXPTMember8Label {
            get {
                return ResourceManager.GetString("DQXPTMember8Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   용기사과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DRG {
            get {
                return ResourceManager.GetString("DRG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;DRG&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DRGLabel {
            get {
                return ResourceManager.GetString("DRGLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   암흑기사과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DRK {
            get {
                return ResourceManager.GetString("DRK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;DRK&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DRKLabel {
            get {
                return ResourceManager.GetString("DRKLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   경과 시간과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   경과 초과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ElapsedHeader {
            get {
                return ResourceManager.GetString("ElapsedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   활성화과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   활성화과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string EnabledSpellTimerNoDecimalCheckBox {
            get {
                return ResourceManager.GetString("EnabledSpellTimerNoDecimalCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시전 완료 후 타이머 숨기기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string EraseAfterRecast {
            get {
                return ResourceManager.GetString("EraseAfterRecast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   내보내기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ExportButton {
            get {
                return ResourceManager.GetString("ExportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   내보내기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ExportCSVButton {
            get {
                return ResourceManager.GetString("ExportCSVButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시전시간 확장과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ExtendBeyondOriginalRecastTimeCheckBox {
            get {
                return ResourceManager.GetString("ExtendBeyondOriginalRecastTimeCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   확장 시간 제한과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ExtendLimitLabel {
            get {
                return ResourceManager.GetString("ExtendLimitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시전 위치 고정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FixedPositionSpell {
            get {
                return ResourceManager.GetString("FixedPositionSpell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   어부과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FSH {
            get {
                return ResourceManager.GetString("FSH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   일반과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GeneralTab {
            get {
                return ResourceManager.GetString("GeneralTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   검술사과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GLD {
            get {
                return ResourceManager.GetString("GLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   보석공예사과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GSM {
            get {
                return ResourceManager.GetString("GSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   스킬 이름 숨기기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HideSpellNameCheckBox {
            get {
                return ResourceManager.GetString("HideSpellNameCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   비활성화 시 오버레이 숨기기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HideWhenNotActiceCheckBox {
            get {
                return ResourceManager.GetString("HideWhenNotActiceCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   수평 레이아웃과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HorizontalLayout {
            get {
                return ResourceManager.GetString("HorizontalLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HP과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HPHeader {
            get {
                return ResourceManager.GetString("HPHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   로그 일치 시 소리 재생과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ImmediateSoundEffect {
            get {
                return ResourceManager.GetString("ImmediateSoundEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   가져오기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ImportButton {
            get {
                return ResourceManager.GetString("ImportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   초기값으로 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InitializationButton {
            get {
                return ResourceManager.GetString("InitializationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   실행 중과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string IsRunning {
            get {
                return ResourceManager.GetString("IsRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   정지 중과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string IsStopping {
            get {
                return ResourceManager.GetString("IsStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   언어 (Language)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   줄과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LinesLabel {
            get {
                return ResourceManager.GetString("LinesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   창술사과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LNC {
            get {
                return ResourceManager.GetString("LNC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   색상표 가져오기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LoadColorSet {
            get {
                return ResourceManager.GetString("LoadColorSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XML 파일에 오류가 있습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LoadXMLError {
            get {
                return ResourceManager.GetString("LoadXMLError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   위치과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   로그과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LogHeader {
            get {
                return ResourceManager.GetString("LogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   로그과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LogLabel {
            get {
                return ResourceManager.GetString("LogLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   로그 처리 대기시간과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LogPollSleepIntervalLabel {
            get {
                return ResourceManager.GetString("LogPollSleepIntervalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   타입과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LogTypeHeader {
            get {
                return ResourceManager.GetString("LogTypeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   가죽공예사과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LTW {
            get {
                return ResourceManager.GetString("LTW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   여백과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Margin {
            get {
                return ResourceManager.GetString("Margin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This looks for partial matches in the game log\nExample)\r\nIf you chose &quot;freezing sword&quot; as your matching text.\nAnd the log contains the string &quot;Shiva uses stance of freezing sword&quot;.\n→ Then this would match that line in the game log.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MatchingKeywordExplanationTooltip {
            get {
                return ResourceManager.GetString("MatchingKeywordExplanationTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   로그 일치 시 보여주기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MatchingLogWordLabel {
            get {
                return ResourceManager.GetString("MatchingLogWordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   로그 일치 시 확장하기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MatchingLogWordToExpandLabel {
            get {
                return ResourceManager.GetString("MatchingLogWordToExpandLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   로그 일치 시 사라지기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MatchingWordsToHide {
            get {
                return ResourceManager.GetString("MatchingWordsToHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   지연 표시과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MatchLogLabel {
            get {
                return ResourceManager.GetString("MatchLogLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   기공사과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MCH {
            get {
                return ResourceManager.GetString("MCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;MCH&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MCHLabel {
            get {
                return ResourceManager.GetString("MCHLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;me&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MeLabel {
            get {
                return ResourceManager.GetString("MeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;2&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Member2Label {
            get {
                return ResourceManager.GetString("Member2Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;3&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Member3Label {
            get {
                return ResourceManager.GetString("Member3Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;4&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Member4Label {
            get {
                return ResourceManager.GetString("Member4Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;5&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Member5Label {
            get {
                return ResourceManager.GetString("Member5Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;6&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Member6Label {
            get {
                return ResourceManager.GetString("Member6Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;7&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Member7Label {
            get {
                return ResourceManager.GetString("Member7Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;8&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Member8Label {
            get {
                return ResourceManager.GetString("Member8Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   틱 표시를 보이기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MessageOnTickerLabel {
            get {
                return ResourceManager.GetString("MessageOnTickerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   밀리초과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Millisecond {
            get {
                return ResourceManager.GetString("Millisecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   광부과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MIN {
            get {
                return ResourceManager.GetString("MIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   몽크과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MNK {
            get {
                return ResourceManager.GetString("MNK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;MNK&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MNKLabel {
            get {
                return ResourceManager.GetString("MNKLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   화면과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MonitorTabPage {
            get {
                return ResourceManager.GetString("MonitorTabPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   도끼술사과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MRD {
            get {
                return ResourceManager.GetString("MRD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   새 표식과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NewTelop {
            get {
                return ResourceManager.GetString("NewTelop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An exception occurred in the confirmation of updates: {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NewVersionError {
            get {
                return ResourceManager.GetString("NewVersionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   새 버전 {0}이 출시되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NewVersionReleased {
            get {
                return ResourceManager.GetString("NewVersionReleased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   닌자과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NIN {
            get {
                return ResourceManager.GetString("NIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;NIN&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NINLabel {
            get {
                return ResourceManager.GetString("NINLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string No1Label {
            get {
                return ResourceManager.GetString("No1Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string No2Label {
            get {
                return ResourceManager.GetString("No2Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ※ 로그 일치 시 ACT 스펠타이머로 알림 (실험적인 기능)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NotifyNormalSpellTimerExplainLabel {
            get {
                return ResourceManager.GetString("NotifyNormalSpellTimerExplainLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   스펠타이머로 알림과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NotifyNormalSpellTimerLabel {
            get {
                return ResourceManager.GetString("NotifyNormalSpellTimerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   순번과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NumberHeader {
            get {
                return ResourceManager.GetString("NumberHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   확인과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OKButton {
            get {
                return ResourceManager.GetString("OKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   0:투명, 255:불투명과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OpacityDescription {
            get {
                return ResourceManager.GetString("OpacityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OptionTabPageTitle {
            get {
                return ResourceManager.GetString("OptionTabPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   재사용 대기 시간 겹쳐서 표시하기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OverlapRecastTimeCheckBox {
            get {
                return ResourceManager.GetString("OverlapRecastTimeCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   오버레이 표시 : 비표시중과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OverlayDisplaySwitchIsOff {
            get {
                return ResourceManager.GetString("OverlayDisplaySwitchIsOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   오버레이 표시 : 표시중과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OverlayDisplaySwitchIsOn {
            get {
                return ResourceManager.GetString("OverlayDisplaySwitchIsOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   파이널판타지가 실행중이지 않을때도 오버레이 사용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OverlayForceVisibleCheckBox {
            get {
                return ResourceManager.GetString("OverlayForceVisibleCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   타이머 완료 시 표시할 텍스트 (이상)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OverTextLabel {
            get {
                return ResourceManager.GetString("OverTextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   그룹명과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PanelNameLabel {
            get {
                return ResourceManager.GetString("PanelNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ※ &lt;2&gt; - &lt;8&gt; 를 사용할 수 있지만 순서가 다를 수 있음.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PartyMemberNumberExplainLabel {
            get {
                return ResourceManager.GetString("PartyMemberNumberExplainLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   파티원 이름 매칭 사용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PartyPronounLabel {
            get {
                return ResourceManager.GetString("PartyPronounLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ♪과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PlayButton {
            get {
                return ResourceManager.GetString("PlayButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   나이트과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PLD {
            get {
                return ResourceManager.GetString("PLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;PLD&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PLDLabel {
            get {
                return ResourceManager.GetString("PLDLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   기다려주세요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PleaseWait1 {
            get {
                return ResourceManager.GetString("PleaseWait1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   기다려주세요 .과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PleaseWait2 {
            get {
                return ResourceManager.GetString("PleaseWait2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   기다려주세요 . .과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PleaseWait3 {
            get {
                return ResourceManager.GetString("PleaseWait3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   기다려주세요 . . .과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PleaseWait4 {
            get {
                return ResourceManager.GetString("PleaseWait4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   기다려주세요 . . . .과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PleaseWait5 {
            get {
                return ResourceManager.GetString("PleaseWait5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ※ 더 작은 쪽을 우선과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PriorityExplainLabel {
            get {
                return ResourceManager.GetString("PriorityExplainLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   진행 막대 형태과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ProgressBarAppearance {
            get {
                return ResourceManager.GetString("ProgressBarAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   격투사과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PUG {
            get {
                return ResourceManager.GetString("PUG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   타이머 종료 후 표시할 텍스트 (완료 시)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReadyTextLabel {
            get {
                return ResourceManager.GetString("ReadyTextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   타이머 초과 시 표시할 텍스트과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RecastCompleteSoundEffect {
            get {
                return ResourceManager.GetString("RecastCompleteSoundEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   재사용 대기 시간 (초)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RecastTimeLabel {
            get {
                return ResourceManager.GetString("RecastTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   재사용 대기 시간 초기화 시 아이콘 반짝임과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReduceIconBrightness {
            get {
                return ResourceManager.GetString("ReduceIconBrightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   재사용 대기 시간 초기화 시 아이콘 반짝임과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReduceIconBrightnessCheckBox {
            get {
                return ResourceManager.GetString("ReduceIconBrightnessCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReferenceButton {
            get {
                return ResourceManager.GetString("ReferenceButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   정규식 매칭은 기본적으로 비활성입니다.\n성능 향상을 위해서는 정규 표현식 대신 부분일치를 사용하시기 바랍니다. (c# Regex가 느림의 의미인 듯)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RegularExpressionExplanationTooltip {
            get {
                return ResourceManager.GetString("RegularExpressionExplanationTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   툴팁 메세지 삭제과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RemoveTooltipSymbolsLabel {
            get {
                return ResourceManager.GetString("RemoveTooltipSymbolsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   반복과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RepeatCheckBox {
            get {
                return ResourceManager.GetString("RepeatCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ※ 변경 시 재시작 필요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RequiresRestart {
            get {
                return ResourceManager.GetString("RequiresRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   정말로 모든 설정과 틱 표시를 초기화 하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ResetAllPrompt {
            get {
                return ResourceManager.GetString("ResetAllPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   전멸 시 카운터 재설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ResetOnWipeOutLabel {
            get {
                return ResourceManager.GetString("ResetOnWipeOutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   모든 스펠타이머 막대 크기 초기화과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ResetSpellBarSize {
            get {
                return ResourceManager.GetString("ResetSpellBarSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   모든 스펠타이머 색상 초기화과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ResetSpellColor {
            get {
                return ResourceManager.GetString("ResetSpellColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   모든 스펠타이머 글씨체 초기화과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ResetSpellFont {
            get {
                return ResourceManager.GetString("ResetSpellFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   모든 스펠타이머 표식 초기화과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ResetTelopColor {
            get {
                return ResourceManager.GetString("ResetTelopColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   모든 스펠타이머 표식 글씨체 초기화과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ResetTelopFont {
            get {
                return ResourceManager.GetString("ResetTelopFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   막대 진행방향 바꾸기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReverseDirectionCheckbox {
            get {
                return ResourceManager.GetString("ReverseDirectionCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   쌍검사과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ROG {
            get {
                return ResourceManager.GetString("ROG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   예시 스킬과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SampleSpell {
            get {
                return ResourceManager.GetString("SampleSpell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   예시 타이머과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SampleTelop {
            get {
                return ResourceManager.GetString("SampleTelop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   색상표 저장과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SaveColorSet {
            get {
                return ResourceManager.GetString("SaveColorSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   로그 저장과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SaveLogLabel {
            get {
                return ResourceManager.GetString("SaveLogLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   학자과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SCH {
            get {
                return ResourceManager.GetString("SCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;SCH&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SCHLabel {
            get {
                return ResourceManager.GetString("SCHLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   화면 갱신 시간과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ScreenUpdateTimeLabel {
            get {
                return ResourceManager.GetString("ScreenUpdateTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   초과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SecondsLabel {
            get {
                return ResourceManager.GetString("SecondsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   초 후과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SecondsLater {
            get {
                return ResourceManager.GetString("SecondsLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   모두 선택과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   직업 필터과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SelectJobButton {
            get {
                return ResourceManager.GetString("SelectJobButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ※ 적용할 직업을 체크하세요 (체크하지 않으면 필터되지 않음)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SelectJobSubtitle {
            get {
                return ResourceManager.GetString("SelectJobSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   적용 직업 선택창과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SelectJobTitle {
            get {
                return ResourceManager.GetString("SelectJobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   지역 필터과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SelectZoneButton {
            get {
                return ResourceManager.GetString("SelectZoneButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   지역을 선택하세요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SelectZoneTitle {
            get {
                return ResourceManager.GetString("SelectZoneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시작 조건과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SetConditionForStartButton {
            get {
                return ResourceManager.GetString("SetConditionForStartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   조건을 선택하세요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SetConditionTitle {
            get {
                return ResourceManager.GetString("SetConditionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이 로그를 기점으로 0초 설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SetLogOrigin {
            get {
                return ResourceManager.GetString("SetLogOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   타이머와 진행 막대를 표시과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ShowProgressBarCheckBox {
            get {
                return ResourceManager.GetString("ShowProgressBarCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   정규식을 단순화과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SimpleRegexLabel {
            get {
                return ResourceManager.GetString("SimpleRegexLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   소환사과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SMN {
            get {
                return ResourceManager.GetString("SMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;SMN&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SMNLabel {
            get {
                return ResourceManager.GetString("SMNLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   다음 스펠까지 타이머 정렬과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SortByRecastOrder {
            get {
                return ResourceManager.GetString("SortByRecastOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   완료되기 N초 전 소리 재생과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SoundEffectBeforeComplete {
            get {
                return ResourceManager.GetString("SoundEffectBeforeComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An exception occurred in the regeneration of ACT.SpecialSpellTimer Sound.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SoundError {
            get {
                return ResourceManager.GetString("SoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   소리 재생까지 대기시간(초)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SoundInSeconds {
            get {
                return ResourceManager.GetString("SoundInSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   초 전과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SoundInSecondsBefore {
            get {
                return ResourceManager.GetString("SoundInSecondsBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   기간과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SpanHeader {
            get {
                return ResourceManager.GetString("SpanHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ▶과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SpeakButton {
            get {
                return ResourceManager.GetString("SpeakButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ※ PC 사양에 맞춰 설정하십시오과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SpecsLabel {
            get {
                return ResourceManager.GetString("SpecsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   모든 스펠 타이머를 지우시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SpellClearAllPrompt {
            get {
                return ResourceManager.GetString("SpellClearAllPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   스킬 아이콘과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SpellIconLabel {
            get {
                return ResourceManager.GetString("SpellIconLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   스킬 아이콘 크기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SpellIconSizeLabel {
            get {
                return ResourceManager.GetString("SpellIconSizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   스킬 이름과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SpellNameLabel {
            get {
                return ResourceManager.GetString("SpellNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ※ 그림 객체 성능 향상 (재시작 필요)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SpellTimerFormatExplainLabel {
            get {
                return ResourceManager.GetString("SpellTimerFormatExplainLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   재사용 대기시간 정수로 표시과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SpellTimerFormatLabel {
            get {
                return ResourceManager.GetString("SpellTimerFormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An exception occurred in the Refresh of ACT.SpecialSpellTimer spell timer Window.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SpellTimerRefreshError {
            get {
                return ResourceManager.GetString("SpellTimerRefreshError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   스펠 타이머과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SpellTimerTabTitle {
            get {
                return ResourceManager.GetString("SpellTimerTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   스페스페과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SupeSupe {
            get {
                return ResourceManager.GetString("SupeSupe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   스킬 보이기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SwitchOverlayButton {
            get {
                return ResourceManager.GetString("SwitchOverlayButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   정말로 모든 틱 표시를 지우시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TelopClearAllPrompt {
            get {
                return ResourceManager.GetString("TelopClearAllPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   모든 틱커 표시\n현재 : OFF과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TelopDisplaySwitchIsOff {
            get {
                return ResourceManager.GetString("TelopDisplaySwitchIsOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   모든 틱커 표시\n현재 : ON과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TelopDisplaySwitchIsOn {
            get {
                return ResourceManager.GetString("TelopDisplaySwitchIsOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   For the displayed message, {COUNT} will be replaced by the number of seconds until the ticker completes.\n{COUNT} → displays a single decimal point (eg. 30.0)\n{COUNT0} → display no decimals (eg. 30)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TelopMessageExplanationTooltip {
            get {
                return ResourceManager.GetString("TelopMessageExplanationTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   틱 표시과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TelopTabPageTitle {
            get {
                return ResourceManager.GetString("TelopTabPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   글자 읽어주기 보조도구과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TextToSpeakLabel {
            get {
                return ResourceManager.GetString("TextToSpeakLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   주술사과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string THM {
            get {
                return ResourceManager.GetString("THM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   틱 표시 이름과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TickerName {
            get {
                return ResourceManager.GetString("TickerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   타임스탬프과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TimestampHeader {
            get {
                return ResourceManager.GetString("TimestampHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   스킬 이름 (표시명)이 다른 경우 인스턴스화 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ToInstanceCheckBox {
            get {
                return ResourceManager.GetString("ToInstanceCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   오버레이 투명도과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TransmitOverlay {
            get {
                return ResourceManager.GetString("TransmitOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   판올림과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   저장과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UpdateButton {
            get {
                return ResourceManager.GetString("UpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   스킬의 이름을 정해주세요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UpdateSpellNameTitle {
            get {
                return ResourceManager.GetString("UpdateSpellNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   패널의 이름을 정해주세요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UpdateSpellPanelTitle {
            get {
                return ResourceManager.GetString("UpdateSpellPanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   틱 표시의 이름을 정해주세요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UpdateTelopNameTitle {
            get {
                return ResourceManager.GetString("UpdateTelopNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   파이널 판타지 14 이외에서 사용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UseOtherThanFFXIVCheckbox {
            get {
                return ResourceManager.GetString("UseOtherThanFFXIVCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   정규식 사용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UseRegex {
            get {
                return ResourceManager.GetString("UseRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   전사과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WAR {
            get {
                return ResourceManager.GetString("WAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;WAR&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WARLabel {
            get {
                return ResourceManager.GetString("WARLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An exception occurred in the Watch foreground window.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WatchActiveError {
            get {
                return ResourceManager.GetString("WatchActiveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   소리 효과과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WaveSoundLabel {
            get {
                return ResourceManager.GetString("WaveSoundLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   백마도사과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WHM {
            get {
                return ResourceManager.GetString("WHM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;WHM&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WHMLabel {
            get {
                return ResourceManager.GetString("WHMLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   재봉사과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WVR {
            get {
                return ResourceManager.GetString("WVR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   X과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string X {
            get {
                return ResourceManager.GetString("X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XML files (*.xml)|*.xml|All files (*.*)|*.*과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string XmlFileFilter {
            get {
                return ResourceManager.GetString("XmlFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Y과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Y {
            get {
                return ResourceManager.GetString("Y", resourceCulture);
            }
        }
    }
}
