//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACT.SpecialSpellTimer.resources.strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings_JP {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_JP() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ACT.SpecialSpellTimer.resources.strings.Strings-JP", typeof(Strings_JP).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 巴術士.
        /// </summary>
        internal static string ACN {
            get {
                return ResourceManager.GetString("ACN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACT.SpecialSpellTimer Assemblyの解決で例外が発生しました。.
        /// </summary>
        internal static string ACTAssemblyError {
            get {
                return ResourceManager.GetString("ACTAssemblyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アクション.
        /// </summary>
        internal static string ActionHeader {
            get {
                return ResourceManager.GetString("ActionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アクター.
        /// </summary>
        internal static string ActorHeader {
            get {
                return ResourceManager.GetString("ActorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACT.SpecialSpellTimer プラグインの初期化で例外が発生しました。.
        /// </summary>
        internal static string ACTPluginStartError {
            get {
                return ResourceManager.GetString("ACTPluginStartError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACT.SpecialSpellTimer プラグインの終了で例外が発生しました。.
        /// </summary>
        internal static string ACTPluginStopError {
            get {
                return ResourceManager.GetString("ACTPluginStopError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 追加.
        /// </summary>
        internal static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 継続的にマッチさせてメッセージを追加表示する.
        /// </summary>
        internal static string AddMessageCheckBox {
            get {
                return ResourceManager.GetString("AddMessageCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アラーム及びTTS.
        /// </summary>
        internal static string AlarmTab {
            get {
                return ResourceManager.GetString("AlarmTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 錬金術師.
        /// </summary>
        internal static string ALC {
            get {
                return ResourceManager.GetString("ALC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全てOFF.
        /// </summary>
        internal static string AllOffButton {
            get {
                return ResourceManager.GetString("AllOffButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全てON.
        /// </summary>
        internal static string AllOnButton {
            get {
                return ResourceManager.GetString("AllOnButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to テロップを常に表示する.
        /// </summary>
        internal static string AlwaysDisplayTelop {
            get {
                return ResourceManager.GetString("AlwaysDisplayTelop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分析する.
        /// </summary>
        internal static string AnalyzeCombat {
            get {
                return ResourceManager.GetString("AnalyzeCombat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 適用する.
        /// </summary>
        internal static string ApplyButton {
            get {
                return ResourceManager.GetString("ApplyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 弓術士.
        /// </summary>
        internal static string ARC {
            get {
                return ResourceManager.GetString("ARC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 甲冑師.
        /// </summary>
        internal static string ARM {
            get {
                return ResourceManager.GetString("ARM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 占星術師.
        /// </summary>
        internal static string AST {
            get {
                return ResourceManager.GetString("AST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;AST&gt;.
        /// </summary>
        internal static string ASTLabel {
            get {
                return ResourceManager.GetString("ASTLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 逆(遠い順)にする.
        /// </summary>
        internal static string AutoSortReverseCheckbox {
            get {
                return ResourceManager.GetString("AutoSortReverseCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 背景色のアルファチャンネル.
        /// </summary>
        internal static string BackgroundColorAlphaTitle {
            get {
                return ResourceManager.GetString("BackgroundColorAlphaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ﾊﾞｰのｻｲｽﾞ.
        /// </summary>
        internal static string BarSize {
            get {
                return ResourceManager.GetString("BarSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 黒魔道士.
        /// </summary>
        internal static string BLM {
            get {
                return ResourceManager.GetString("BLM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;BLM&gt;.
        /// </summary>
        internal static string BLMLabel {
            get {
                return ResourceManager.GetString("BLMLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 園芸師.
        /// </summary>
        internal static string BOT {
            get {
                return ResourceManager.GetString("BOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 吟遊詩人.
        /// </summary>
        internal static string BRD {
            get {
                return ResourceManager.GetString("BRD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;BRD&gt;.
        /// </summary>
        internal static string BRDLabel {
            get {
                return ResourceManager.GetString("BRDLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 鍛冶師.
        /// </summary>
        internal static string BSM {
            get {
                return ResourceManager.GetString("BSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to バッファのサイズ.
        /// </summary>
        internal static string BufferSize {
            get {
                return ResourceManager.GetString("BufferSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to キャンセル.
        /// </summary>
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 背景色のアルファチャンネルを変更する.
        /// </summary>
        internal static string ChangeBackgroundAlpha {
            get {
                return ResourceManager.GetString("ChangeBackgroundAlpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 背景色を変更する.
        /// </summary>
        internal static string ChangeBackgroundColor {
            get {
                return ResourceManager.GetString("ChangeBackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to バーの色を変更する.
        /// </summary>
        internal static string ChangeBarColor {
            get {
                return ResourceManager.GetString("ChangeBarColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to バーのアウトラインの色を変更する.
        /// </summary>
        internal static string ChangeBarOutlineColor {
            get {
                return ResourceManager.GetString("ChangeBarOutlineColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ※右クリックで変更.
        /// </summary>
        internal static string ChangeByRightClicking {
            get {
                return ResourceManager.GetString("ChangeByRightClicking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to フォントを変更する.
        /// </summary>
        internal static string ChangeFont {
            get {
                return ResourceManager.GetString("ChangeFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to フォントの色を変更する.
        /// </summary>
        internal static string ChangeFontColor {
            get {
                return ResourceManager.GetString("ChangeFontColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to フォントのアウトラインの色を変更する.
        /// </summary>
        internal static string ChangeFontOutlineColor {
            get {
                return ResourceManager.GetString("ChangeFontOutlineColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 警告フォントの色を変更する.
        /// </summary>
        internal static string ChangeWarningFontColor {
            get {
                return ResourceManager.GetString("ChangeWarningFontColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 警告フォントのアウトラインカラーを変更する.
        /// </summary>
        internal static string ChangeWarningFontOutlineColor {
            get {
                return ResourceManager.GetString("ChangeWarningFontOutlineColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全て削除.
        /// </summary>
        internal static string ClearAllButton {
            get {
                return ResourceManager.GetString("ClearAllButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to クリックスルー.
        /// </summary>
        internal static string ClickThrough {
            get {
                return ResourceManager.GetString("ClickThrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 幻術士.
        /// </summary>
        internal static string CNJ {
            get {
                return ResourceManager.GetString("CNJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 戦闘アナライザ.
        /// </summary>
        internal static string CombatAnalyzerTabTitle {
            get {
                return ResourceManager.GetString("CombatAnalyzerTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログを解析しています . . ..
        /// </summary>
        internal static string CombatAnalyzing {
            get {
                return ResourceManager.GetString("CombatAnalyzing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分析用に敵の行動を記録する.
        /// </summary>
        internal static string CombatLogEnabledCheckBox {
            get {
                return ResourceManager.GetString("CombatLogEnabledCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 「, (カンマ)」で改行になります.
        /// </summary>
        internal static string CommaLineBreakExplain {
            get {
                return ResourceManager.GetString("CommaLineBreakExplain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログをコピーする.
        /// </summary>
        internal static string CopyLog {
            get {
                return ResourceManager.GetString("CopyLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログの詳細をコピーする.
        /// </summary>
        internal static string CopyLogDetail {
            get {
                return ResourceManager.GetString("CopyLogDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 木工師.
        /// </summary>
        internal static string CRP {
            get {
                return ResourceManager.GetString("CRP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 調理師.
        /// </summary>
        internal static string CUL {
            get {
                return ResourceManager.GetString("CUL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ディレイ後に鳴らすサウンド.
        /// </summary>
        internal static string DelayedSoundEffect {
            get {
                return ResourceManager.GetString("DelayedSoundEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログにマッチしてｎ秒後に鳴らすサウンド.
        /// </summary>
        internal static string DelayedSoundEffectAfterMatch {
            get {
                return ResourceManager.GetString("DelayedSoundEffectAfterMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 削除.
        /// </summary>
        internal static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FCから始まるPacketDumpも解析対象にする.
        /// </summary>
        internal static string DetectPacketDumpLabel {
            get {
                return ResourceManager.GetString("DetectPacketDumpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ※0にすると無効（消去しない）.
        /// </summary>
        internal static string DisableWhenClear {
            get {
                return ResourceManager.GetString("DisableWhenClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 表示順.
        /// </summary>
        internal static string DisplayOrderLabel {
            get {
                return ResourceManager.GetString("DisplayOrderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 残り時間をプログレスバーで表示する.
        /// </summary>
        internal static string DisplayRemainingTimeCheckBox {
            get {
                return ResourceManager.GetString("DisplayRemainingTimeCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 秒間表示する.
        /// </summary>
        internal static string DisplaySeconds {
            get {
                return ResourceManager.GetString("DisplaySeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to リキャスト後に消去しない.
        /// </summary>
        internal static string DontHideCheckBox {
            get {
                return ResourceManager.GetString("DontHideCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ダウンロードしますか？.
        /// </summary>
        internal static string DownloadPrompt {
            get {
                return ResourceManager.GetString("DownloadPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DQX向け機能を有効にする.
        /// </summary>
        internal static string DQXOptionEnabledCheckBox {
            get {
                return ResourceManager.GetString("DQXOptionEnabledCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DQX向けオプション.
        /// </summary>
        internal static string DQXOptionTabPage {
            get {
                return ResourceManager.GetString("DQXOptionTabPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;me&gt; : プレイヤー名(パーティメンバ1).
        /// </summary>
        internal static string DQXPlayerNameLabel {
            get {
                return ResourceManager.GetString("DQXPlayerNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;2&gt; : パーティメンバ2.
        /// </summary>
        internal static string DQXPTMember2Label {
            get {
                return ResourceManager.GetString("DQXPTMember2Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;3&gt; : パーティメンバ3.
        /// </summary>
        internal static string DQXPTMember3Label {
            get {
                return ResourceManager.GetString("DQXPTMember3Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;4&gt; : パーティメンバ4.
        /// </summary>
        internal static string DQXPTMember4Label {
            get {
                return ResourceManager.GetString("DQXPTMember4Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;5&gt; : パーティメンバ5.
        /// </summary>
        internal static string DQXPTMember5Label {
            get {
                return ResourceManager.GetString("DQXPTMember5Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;6&gt; : パーティメンバ6.
        /// </summary>
        internal static string DQXPTMember6Label {
            get {
                return ResourceManager.GetString("DQXPTMember6Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;7&gt; : パーティメンバ7.
        /// </summary>
        internal static string DQXPTMember7Label {
            get {
                return ResourceManager.GetString("DQXPTMember7Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;8&gt; : パーティメンバ8.
        /// </summary>
        internal static string DQXPTMember8Label {
            get {
                return ResourceManager.GetString("DQXPTMember8Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 竜騎士.
        /// </summary>
        internal static string DRG {
            get {
                return ResourceManager.GetString("DRG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;DRG&gt;.
        /// </summary>
        internal static string DRGLabel {
            get {
                return ResourceManager.GetString("DRGLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暗黒騎士.
        /// </summary>
        internal static string DRK {
            get {
                return ResourceManager.GetString("DRK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;DRK&gt;.
        /// </summary>
        internal static string DRKLabel {
            get {
                return ResourceManager.GetString("DRKLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 秒後から.
        /// </summary>
        internal static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 経過秒.
        /// </summary>
        internal static string ElapsedHeader {
            get {
                return ResourceManager.GetString("ElapsedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 有効.
        /// </summary>
        internal static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 有効.
        /// </summary>
        internal static string EnabledSpellTimerNoDecimalCheckBox {
            get {
                return ResourceManager.GetString("EnabledSpellTimerNoDecimalCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to リキャスト完了後に消去する.
        /// </summary>
        internal static string EraseAfterRecast {
            get {
                return ResourceManager.GetString("EraseAfterRecast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string ExportButton {
            get {
                return ResourceManager.GetString("ExportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV保存.
        /// </summary>
        internal static string ExportCSVButton {
            get {
                return ResourceManager.GetString("ExportCSVButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 元のリキャストタイムを超えて延長する.
        /// </summary>
        internal static string ExtendBeyondOriginalRecastTimeCheckBox {
            get {
                return ResourceManager.GetString("ExtendBeyondOriginalRecastTimeCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 秒を上限とする.
        /// </summary>
        internal static string ExtendLimitLabel {
            get {
                return ResourceManager.GetString("ExtendLimitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スペル位置を固定する.
        /// </summary>
        internal static string FixedPositionSpell {
            get {
                return ResourceManager.GetString("FixedPositionSpell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 漁師.
        /// </summary>
        internal static string FSH {
            get {
                return ResourceManager.GetString("FSH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全般.
        /// </summary>
        internal static string GeneralTab {
            get {
                return ResourceManager.GetString("GeneralTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 剣術士.
        /// </summary>
        internal static string GLD {
            get {
                return ResourceManager.GetString("GLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 彫金師.
        /// </summary>
        internal static string GSM {
            get {
                return ResourceManager.GetString("GSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スペル名を表示しない.
        /// </summary>
        internal static string HideSpellNameCheckBox {
            get {
                return ResourceManager.GetString("HideSpellNameCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 非アクティブのときオーバーレイを隠す.
        /// </summary>
        internal static string HideWhenNotActiceCheckBox {
            get {
                return ResourceManager.GetString("HideWhenNotActiceCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 水平レイアウト.
        /// </summary>
        internal static string HorizontalLayout {
            get {
                return ResourceManager.GetString("HorizontalLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HP.
        /// </summary>
        internal static string HPHeader {
            get {
                return ResourceManager.GetString("HPHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログにマッチした直後に鳴らすサウンド.
        /// </summary>
        internal static string ImmediateSoundEffect {
            get {
                return ResourceManager.GetString("ImmediateSoundEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string ImportButton {
            get {
                return ResourceManager.GetString("ImportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 初期化.
        /// </summary>
        internal static string InitializationButton {
            get {
                return ResourceManager.GetString("InitializationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 稼働中.
        /// </summary>
        internal static string IsRunning {
            get {
                return ResourceManager.GetString("IsRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 停止中.
        /// </summary>
        internal static string IsStopping {
            get {
                return ResourceManager.GetString("IsStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 言語 (Language).
        /// </summary>
        internal static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combat Log Analyze.
        /// </summary>
        internal static string lblCombatAnalyzer {
            get {
                return ResourceManager.GetString("lblCombatAnalyzer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party Member Alarm.
        /// </summary>
        internal static string lblDQX {
            get {
                return ResourceManager.GetString("lblDQX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Setting.
        /// </summary>
        internal static string lblLanguage {
            get {
                return ResourceManager.GetString("lblLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor.
        /// </summary>
        internal static string lblMonitor {
            get {
                return ResourceManager.GetString("lblMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spell Timer Setting.
        /// </summary>
        internal static string lblSpellTimer {
            get {
                return ResourceManager.GetString("lblSpellTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 行.
        /// </summary>
        internal static string LinesLabel {
            get {
                return ResourceManager.GetString("LinesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スペシャルスペルタイマ(スペスペ).
        /// </summary>
        internal static string LN_Tabname {
            get {
                return ResourceManager.GetString("LN_Tabname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 槍術士.
        /// </summary>
        internal static string LNC {
            get {
                return ResourceManager.GetString("LNC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配色を読み込む.
        /// </summary>
        internal static string LoadColorSet {
            get {
                return ResourceManager.GetString("LoadColorSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XMLファイルの読み込みで例外が発生しました.
        /// </summary>
        internal static string LoadXMLError {
            get {
                return ResourceManager.GetString("LoadXMLError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 位置.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログ.
        /// </summary>
        internal static string LogHeader {
            get {
                return ResourceManager.GetString("LogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        internal static string LogLabel {
            get {
                return ResourceManager.GetString("LogLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログ処理の最短間隔.
        /// </summary>
        internal static string LogPollSleepIntervalLabel {
            get {
                return ResourceManager.GetString("LogPollSleepIntervalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        internal static string LogTabPage {
            get {
                return ResourceManager.GetString("LogTabPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 種類.
        /// </summary>
        internal static string LogTypeHeader {
            get {
                return ResourceManager.GetString("LogTypeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 革細工師.
        /// </summary>
        internal static string LTW {
            get {
                return ResourceManager.GetString("LTW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to マージン.
        /// </summary>
        internal static string Margin {
            get {
                return ResourceManager.GetString("Margin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログに対して部分一致でマッチングします\n例)\nマッチングワード : は「凍てつく剣」の構え\nログ : シヴァは「凍てつく剣」の構え。\n→ マッチします.
        /// </summary>
        internal static string MatchingKeywordExplanationTooltip {
            get {
                return ResourceManager.GetString("MatchingKeywordExplanationTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログに対するマッチングワード.
        /// </summary>
        internal static string MatchingLogWordLabel {
            get {
                return ResourceManager.GetString("MatchingLogWordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 延長するマッチングワード.
        /// </summary>
        internal static string MatchingLogWordToExpandLabel {
            get {
                return ResourceManager.GetString("MatchingLogWordToExpandLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 非表示にするマッチングワード.
        /// </summary>
        internal static string MatchingWordsToHide {
            get {
                return ResourceManager.GetString("MatchingWordsToHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログにマッチして・・・.
        /// </summary>
        internal static string MatchLogLabel {
            get {
                return ResourceManager.GetString("MatchLogLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 機工士.
        /// </summary>
        internal static string MCH {
            get {
                return ResourceManager.GetString("MCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;MCH&gt;.
        /// </summary>
        internal static string MCHLabel {
            get {
                return ResourceManager.GetString("MCHLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;me&gt;.
        /// </summary>
        internal static string MeLabel {
            get {
                return ResourceManager.GetString("MeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;2&gt;.
        /// </summary>
        internal static string Member2Label {
            get {
                return ResourceManager.GetString("Member2Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;3&gt;.
        /// </summary>
        internal static string Member3Label {
            get {
                return ResourceManager.GetString("Member3Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;4&gt;.
        /// </summary>
        internal static string Member4Label {
            get {
                return ResourceManager.GetString("Member4Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;5&gt;.
        /// </summary>
        internal static string Member5Label {
            get {
                return ResourceManager.GetString("Member5Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;6&gt;.
        /// </summary>
        internal static string Member6Label {
            get {
                return ResourceManager.GetString("Member6Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;7&gt;.
        /// </summary>
        internal static string Member7Label {
            get {
                return ResourceManager.GetString("Member7Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;8&gt;.
        /// </summary>
        internal static string Member8Label {
            get {
                return ResourceManager.GetString("Member8Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to テロップに表示するメッセージ.
        /// </summary>
        internal static string MessageOnTickerLabel {
            get {
                return ResourceManager.GetString("MessageOnTickerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ミリ秒.
        /// </summary>
        internal static string Millisecond {
            get {
                return ResourceManager.GetString("Millisecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 採掘師.
        /// </summary>
        internal static string MIN {
            get {
                return ResourceManager.GetString("MIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to モンク.
        /// </summary>
        internal static string MNK {
            get {
                return ResourceManager.GetString("MNK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;MNK&gt;.
        /// </summary>
        internal static string MNKLabel {
            get {
                return ResourceManager.GetString("MNKLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to モニター.
        /// </summary>
        internal static string MonitorTabPage {
            get {
                return ResourceManager.GetString("MonitorTabPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 斧術士.
        /// </summary>
        internal static string MRD {
            get {
                return ResourceManager.GetString("MRD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Telop.
        /// </summary>
        internal static string NewTelop {
            get {
                return ResourceManager.GetString("NewTelop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アップデートの確認で例外が発生しました。{0}.
        /// </summary>
        internal static string NewVersionError {
            get {
                return ResourceManager.GetString("NewVersionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} の新しいバージョンがリリースされています。.
        /// </summary>
        internal static string NewVersionReleased {
            get {
                return ResourceManager.GetString("NewVersionReleased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 忍者.
        /// </summary>
        internal static string NIN {
            get {
                return ResourceManager.GetString("NIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;NIN&gt;.
        /// </summary>
        internal static string NINLabel {
            get {
                return ResourceManager.GetString("NINLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string No1Label {
            get {
                return ResourceManager.GetString("No1Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string No2Label {
            get {
                return ResourceManager.GetString("No2Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ※ログマッチ時に標準のスペルタイマーへの通知が行われます（試験的な機能）.
        /// </summary>
        internal static string NotifyNormalSpellTimerExplainLabel {
            get {
                return ResourceManager.GetString("NotifyNormalSpellTimerExplainLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 標準のスペルタイマーに通知する.
        /// </summary>
        internal static string NotifyNormalSpellTimerLabel {
            get {
                return ResourceManager.GetString("NotifyNormalSpellTimerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string NumberHeader {
            get {
                return ResourceManager.GetString("NumberHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OKButton {
            get {
                return ResourceManager.GetString("OKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0:透明, 255:不透明.
        /// </summary>
        internal static string OpacityDescription {
            get {
                return ResourceManager.GetString("OpacityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to オプション.
        /// </summary>
        internal static string OptionTabPageTitle {
            get {
                return ResourceManager.GetString("OptionTabPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to リキャストタイムを重ねる.
        /// </summary>
        internal static string OverlapRecastTimeCheckBox {
            get {
                return ResourceManager.GetString("OverlapRecastTimeCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to オーバーレイの表示スイッチ\n現在の状態 -&gt; OFF.
        /// </summary>
        internal static string OverlayDisplaySwitchIsOff {
            get {
                return ResourceManager.GetString("OverlayDisplaySwitchIsOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to オーバーレイの表示スイッチ\n現在の状態 -&gt; ON.
        /// </summary>
        internal static string OverlayDisplaySwitchIsOn {
            get {
                return ResourceManager.GetString("OverlayDisplaySwitchIsOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFXIVが起動していなくてもオーバーレイを表示する.
        /// </summary>
        internal static string OverlayForceVisibleCheckBox {
            get {
                return ResourceManager.GetString("OverlayForceVisibleCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スペルタイマが完了した時のテキスト(Over).
        /// </summary>
        internal static string OverTextLabel {
            get {
                return ResourceManager.GetString("OverTextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 表示するパネルの名前.
        /// </summary>
        internal static string PanelNameLabel {
            get {
                return ResourceManager.GetString("PanelNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ※&lt;2&gt;～&lt;8&gt;が使用可能になります。ただし2～8の順序は正しくない場合があります。.
        /// </summary>
        internal static string PartyMemberNumberExplainLabel {
            get {
                return ResourceManager.GetString("PartyMemberNumberExplainLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PTメンバの代名詞を有効にする.
        /// </summary>
        internal static string PartyPronounLabel {
            get {
                return ResourceManager.GetString("PartyPronounLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ♪.
        /// </summary>
        internal static string PlayButton {
            get {
                return ResourceManager.GetString("PlayButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ナイト.
        /// </summary>
        internal static string PLD {
            get {
                return ResourceManager.GetString("PLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;PLD&gt;.
        /// </summary>
        internal static string PLDLabel {
            get {
                return ResourceManager.GetString("PLDLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Wait.
        /// </summary>
        internal static string PleaseWait1 {
            get {
                return ResourceManager.GetString("PleaseWait1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Wait ..
        /// </summary>
        internal static string PleaseWait2 {
            get {
                return ResourceManager.GetString("PleaseWait2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Wait . ..
        /// </summary>
        internal static string PleaseWait3 {
            get {
                return ResourceManager.GetString("PleaseWait3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Wait . . ..
        /// </summary>
        internal static string PleaseWait4 {
            get {
                return ResourceManager.GetString("PleaseWait4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Wait . . . ..
        /// </summary>
        internal static string PleaseWait5 {
            get {
                return ResourceManager.GetString("PleaseWait5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ※より小さいほうが優先.
        /// </summary>
        internal static string PriorityExplainLabel {
            get {
                return ResourceManager.GetString("PriorityExplainLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to プログレスバーの見た目.
        /// </summary>
        internal static string ProgressBarAppearance {
            get {
                return ResourceManager.GetString("ProgressBarAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 格闘士.
        /// </summary>
        internal static string PUG {
            get {
                return ResourceManager.GetString("PUG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 赤魔道士.
        /// </summary>
        internal static string RDM {
            get {
                return ResourceManager.GetString("RDM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;RDM&gt;.
        /// </summary>
        internal static string RDMLabel {
            get {
                return ResourceManager.GetString("RDMLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スペルタイマが完了した時のテキスト(Ready).
        /// </summary>
        internal static string ReadyTextLabel {
            get {
                return ResourceManager.GetString("ReadyTextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to リキャスト完了時に鳴らすサウンド.
        /// </summary>
        internal static string RecastCompleteSoundEffect {
            get {
                return ResourceManager.GetString("RecastCompleteSoundEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スペルのリキャスト時間(秒).
        /// </summary>
        internal static string RecastTimeLabel {
            get {
                return ResourceManager.GetString("RecastTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アイコン暗転時の明るさ.
        /// </summary>
        internal static string ReduceIconBrightness {
            get {
                return ResourceManager.GetString("ReduceIconBrightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to リキャスト中はアイコンを暗くする.
        /// </summary>
        internal static string ReduceIconBrightnessCheckBox {
            get {
                return ResourceManager.GetString("ReduceIconBrightnessCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        internal static string ReferenceButton {
            get {
                return ResourceManager.GetString("ReferenceButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正規表現が無効でも部分一致は既定で有効となっています\n正規表現OFFでの部分一致のほうがパフォーマンスは向上します.
        /// </summary>
        internal static string RegularExpressionExplanationTooltip {
            get {
                return ResourceManager.GetString("RegularExpressionExplanationTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ツールチップ記号を除去する.
        /// </summary>
        internal static string RemoveTooltipSymbolsLabel {
            get {
                return ResourceManager.GetString("RemoveTooltipSymbolsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to リキャスト後に繰り返す.
        /// </summary>
        internal static string RepeatCheckBox {
            get {
                return ResourceManager.GetString("RepeatCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ※再起動が必要.
        /// </summary>
        internal static string RequiresRestart {
            get {
                return ResourceManager.GetString("RequiresRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to あなたはすべての設定とテロップ位置をリセットしてもよろしいですか？.
        /// </summary>
        internal static string ResetAllPrompt {
            get {
                return ResourceManager.GetString("ResetAllPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全滅時にカウントをリセットする.
        /// </summary>
        internal static string ResetOnWipeOutLabel {
            get {
                return ResourceManager.GetString("ResetOnWipeOutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スペルをこのバーサイズで統一する.
        /// </summary>
        internal static string ResetSpellBarSize {
            get {
                return ResourceManager.GetString("ResetSpellBarSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スペルをこの配色で統一する.
        /// </summary>
        internal static string ResetSpellColor {
            get {
                return ResourceManager.GetString("ResetSpellColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スペルをこのフォントで統一する.
        /// </summary>
        internal static string ResetSpellFont {
            get {
                return ResourceManager.GetString("ResetSpellFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to テロップをこの配色で統一する.
        /// </summary>
        internal static string ResetTelopColor {
            get {
                return ResourceManager.GetString("ResetTelopColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to テロップをこのフォントで統一する.
        /// </summary>
        internal static string ResetTelopFont {
            get {
                return ResourceManager.GetString("ResetTelopFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 進行方向を逆にする.
        /// </summary>
        internal static string ReverseDirectionCheckbox {
            get {
                return ResourceManager.GetString("ReverseDirectionCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 双剣士.
        /// </summary>
        internal static string ROG {
            get {
                return ResourceManager.GetString("ROG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 侍.
        /// </summary>
        internal static string SAM {
            get {
                return ResourceManager.GetString("SAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SAM&gt;.
        /// </summary>
        internal static string SAMLabel {
            get {
                return ResourceManager.GetString("SAMLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to サンプルスペル.
        /// </summary>
        internal static string SampleSpell {
            get {
                return ResourceManager.GetString("SampleSpell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to サンプルテロップ.
        /// </summary>
        internal static string SampleTelop {
            get {
                return ResourceManager.GetString("SampleTelop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配色を保存する.
        /// </summary>
        internal static string SaveColorSet {
            get {
                return ResourceManager.GetString("SaveColorSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログを保存する.
        /// </summary>
        internal static string SaveLogLabel {
            get {
                return ResourceManager.GetString("SaveLogLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 学者.
        /// </summary>
        internal static string SCH {
            get {
                return ResourceManager.GetString("SCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SCH&gt;.
        /// </summary>
        internal static string SCHLabel {
            get {
                return ResourceManager.GetString("SCHLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 画面の更新間隔.
        /// </summary>
        internal static string ScreenUpdateTimeLabel {
            get {
                return ResourceManager.GetString("ScreenUpdateTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 秒延長する.
        /// </summary>
        internal static string SecondsLabel {
            get {
                return ResourceManager.GetString("SecondsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 秒後.
        /// </summary>
        internal static string SecondsLater {
            get {
                return ResourceManager.GetString("SecondsLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全て選択.
        /// </summary>
        internal static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ジョブを限定する.
        /// </summary>
        internal static string SelectJobButton {
            get {
                return ResourceManager.GetString("SelectJobButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ※対象とするジョブを限定したい場合はチェックをONにしてください.
        /// </summary>
        internal static string SelectJobSubtitle {
            get {
                return ResourceManager.GetString("SelectJobSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 対象のジョブを選択してください.
        /// </summary>
        internal static string SelectJobTitle {
            get {
                return ResourceManager.GetString("SelectJobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ゾーンを限定する.
        /// </summary>
        internal static string SelectZoneButton {
            get {
                return ResourceManager.GetString("SelectZoneButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 対象のゾーンを選択して下さい.
        /// </summary>
        internal static string SelectZoneTitle {
            get {
                return ResourceManager.GetString("SelectZoneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 開始条件を設定する.
        /// </summary>
        internal static string SetConditionForStartButton {
            get {
                return ResourceManager.GetString("SetConditionForStartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 条件を設定して下さい.
        /// </summary>
        internal static string SetConditionTitle {
            get {
                return ResourceManager.GetString("SetConditionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to このログを経過秒の起点にする.
        /// </summary>
        internal static string SetLogOrigin {
            get {
                return ResourceManager.GetString("SetLogOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スペルリストに表示する.
        /// </summary>
        internal static string ShowProgressBarCheckBox {
            get {
                return ResourceManager.GetString("ShowProgressBarCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正規表現を単純にする.
        /// </summary>
        internal static string SimpleRegexLabel {
            get {
                return ResourceManager.GetString("SimpleRegexLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 召喚士.
        /// </summary>
        internal static string SMN {
            get {
                return ResourceManager.GetString("SMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SMN&gt;.
        /// </summary>
        internal static string SMNLabel {
            get {
                return ResourceManager.GetString("SMNLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to リキャスト完了が近い順でソートする.
        /// </summary>
        internal static string SortByRecastOrder {
            get {
                return ResourceManager.GetString("SortByRecastOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to リキャスト完了ｎ秒前に鳴らすサウンド.
        /// </summary>
        internal static string SoundEffectBeforeComplete {
            get {
                return ResourceManager.GetString("SoundEffectBeforeComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACT.SpecialSpellTimer Soundの再生で例外が発生しました。.
        /// </summary>
        internal static string SoundError {
            get {
                return ResourceManager.GetString("SoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 秒後に鳴らす.
        /// </summary>
        internal static string SoundInSeconds {
            get {
                return ResourceManager.GetString("SoundInSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 秒前に鳴らす.
        /// </summary>
        internal static string SoundInSecondsBefore {
            get {
                return ResourceManager.GetString("SoundInSecondsBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 周期.
        /// </summary>
        internal static string SpanHeader {
            get {
                return ResourceManager.GetString("SpanHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ▶.
        /// </summary>
        internal static string SpeakButton {
            get {
                return ResourceManager.GetString("SpeakButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ※スペックに合わせて設定してください.
        /// </summary>
        internal static string SpecsLabel {
            get {
                return ResourceManager.GetString("SpecsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全てのスペルを削除してよろしいですか？.
        /// </summary>
        internal static string SpellClearAllPrompt {
            get {
                return ResourceManager.GetString("SpellClearAllPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スペルのアイコン.
        /// </summary>
        internal static string SpellIconLabel {
            get {
                return ResourceManager.GetString("SpellIconLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スペルアイコンのサイズ.
        /// </summary>
        internal static string SpellIconSizeLabel {
            get {
                return ResourceManager.GetString("SpellIconSizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スペルの名前.
        /// </summary>
        internal static string SpellNameLabel {
            get {
                return ResourceManager.GetString("SpellNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ※描画の負荷が下がります（要再起動）.
        /// </summary>
        internal static string SpellTimerFormatExplainLabel {
            get {
                return ResourceManager.GetString("SpellTimerFormatExplainLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スペルタイマの秒数を整数表示にする.
        /// </summary>
        internal static string SpellTimerFormatLabel {
            get {
                return ResourceManager.GetString("SpellTimerFormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACT.SpecialSpellTimer スペルタイマWindowのRefreshで例外が発生しました。.
        /// </summary>
        internal static string SpellTimerRefreshError {
            get {
                return ResourceManager.GetString("SpellTimerRefreshError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スペシャルスペルタイマ.
        /// </summary>
        internal static string SpellTimerTabTitle {
            get {
                return ResourceManager.GetString("SpellTimerTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スペスペ.
        /// </summary>
        internal static string SupeSupe {
            get {
                return ResourceManager.GetString("SupeSupe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スペルを表示する.
        /// </summary>
        internal static string SwitchOverlayButton {
            get {
                return ResourceManager.GetString("SwitchOverlayButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail Options.
        /// </summary>
        internal static string tabDetailOptions {
            get {
                return ResourceManager.GetString("tabDetailOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay Options.
        /// </summary>
        internal static string tabOverlayOptions {
            get {
                return ResourceManager.GetString("tabOverlayOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 追加.
        /// </summary>
        internal static string TelopAddButton {
            get {
                return ResourceManager.GetString("TelopAddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全て削除.
        /// </summary>
        internal static string TelopClearAllButton {
            get {
                return ResourceManager.GetString("TelopClearAllButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全てのテロップを削除してよろしいですか？.
        /// </summary>
        internal static string TelopClearAllPrompt {
            get {
                return ResourceManager.GetString("TelopClearAllPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to テロップの表示スイッチ\n現在の状態 -&gt; 通常.
        /// </summary>
        internal static string TelopDisplaySwitchIsOff {
            get {
                return ResourceManager.GetString("TelopDisplaySwitchIsOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to テロップの表示スイッチ\n現在の状態 -&gt; 常に表示(位置調整向け).
        /// </summary>
        internal static string TelopDisplaySwitchIsOn {
            get {
                return ResourceManager.GetString("TelopDisplaySwitchIsOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string TelopExportButton {
            get {
                return ResourceManager.GetString("TelopExportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string TelopImportButton {
            get {
                return ResourceManager.GetString("TelopImportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {COUNT}と記入するとテロップが消えるまでの秒数に置換されます\n{COUNT} → 小数点第1位まで表示。例) 30.0\n{COUNT0} → 整数部のみ表示。例) 30.
        /// </summary>
        internal static string TelopMessageExplanationTooltip {
            get {
                return ResourceManager.GetString("TelopMessageExplanationTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ワンポイントテロップ.
        /// </summary>
        internal static string TelopTabPageTitle {
            get {
                return ResourceManager.GetString("TelopTabPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextToSpeak.
        /// </summary>
        internal static string TextToSpeakLabel {
            get {
                return ResourceManager.GetString("TextToSpeakLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 呪術士.
        /// </summary>
        internal static string THM {
            get {
                return ResourceManager.GetString("THM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to テロップの名前.
        /// </summary>
        internal static string TickerName {
            get {
                return ResourceManager.GetString("TickerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to タイムスタンプ.
        /// </summary>
        internal static string TimestampHeader {
            get {
                return ResourceManager.GetString("TimestampHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スペルの名前(表示テキスト)が異なる場合にインスタンス化する.
        /// </summary>
        internal static string ToInstanceCheckBox {
            get {
                return ResourceManager.GetString("ToInstanceCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to オーバーレイの透過率.
        /// </summary>
        internal static string TransmitOverlay {
            get {
                return ResourceManager.GetString("TransmitOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新.
        /// </summary>
        internal static string UpdateButton {
            get {
                return ResourceManager.GetString("UpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スペル名を入力してください.
        /// </summary>
        internal static string UpdateSpellNameTitle {
            get {
                return ResourceManager.GetString("UpdateSpellNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パネル名を入力してください.
        /// </summary>
        internal static string UpdateSpellPanelTitle {
            get {
                return ResourceManager.GetString("UpdateSpellPanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to テロップの名前を入力してください.
        /// </summary>
        internal static string UpdateTelopNameTitle {
            get {
                return ResourceManager.GetString("UpdateTelopNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFXIV以外で使用する.
        /// </summary>
        internal static string UseOtherThanFFXIVCheckbox {
            get {
                return ResourceManager.GetString("UseOtherThanFFXIVCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正規表現ON.
        /// </summary>
        internal static string UseRegex {
            get {
                return ResourceManager.GetString("UseRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 戦士.
        /// </summary>
        internal static string WAR {
            get {
                return ResourceManager.GetString("WAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;WAR&gt;.
        /// </summary>
        internal static string WARLabel {
            get {
                return ResourceManager.GetString("WARLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 時間が近づくと表示が変化する.
        /// </summary>
        internal static string WarningTimeCheckBox {
            get {
                return ResourceManager.GetString("WarningTimeCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 警告の時間.
        /// </summary>
        internal static string WarningTimeLabel {
            get {
                return ResourceManager.GetString("WarningTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACT.SpecialSpellTimer フォアグラウンドWindowの監視で例外が発生しました。.
        /// </summary>
        internal static string WatchActiveError {
            get {
                return ResourceManager.GetString("WatchActiveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wave.
        /// </summary>
        internal static string WaveSoundLabel {
            get {
                return ResourceManager.GetString("WaveSoundLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 白魔道士.
        /// </summary>
        internal static string WHM {
            get {
                return ResourceManager.GetString("WHM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;WHM&gt;.
        /// </summary>
        internal static string WHMLabel {
            get {
                return ResourceManager.GetString("WHMLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 裁縫師.
        /// </summary>
        internal static string WVR {
            get {
                return ResourceManager.GetString("WVR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        internal static string X {
            get {
                return ResourceManager.GetString("X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XMLファイル (*.xml)|*.xml|全てのファイル (*.*)|*.*.
        /// </summary>
        internal static string XmlFileFilter {
            get {
                return ResourceManager.GetString("XmlFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        internal static string Y {
            get {
                return ResourceManager.GetString("Y", resourceCulture);
            }
        }
    }
}
