//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACT.SpecialSpellTimer.resources.strings {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings_EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_EN() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ACT.SpecialSpellTimer.resources.strings.Strings-EN", typeof(Strings_EN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Arcanist과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ACN {
            get {
                return ResourceManager.GetString("ACN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An exception occurred in ACT.SpecialSpellTimer Assembly resolution.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ACTAssemblyError {
            get {
                return ResourceManager.GetString("ACTAssemblyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Action과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ActionHeader {
            get {
                return ResourceManager.GetString("ActionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Actor과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ActorHeader {
            get {
                return ResourceManager.GetString("ActorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An exception occurred in the initialization of ACT.SpecialSpellTimer plug-ins.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ACTPluginStartError {
            get {
                return ResourceManager.GetString("ACTPluginStartError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An exception occurred at the end of ACT.SpecialSpellTimer plug-ins.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ACTPluginStopError {
            get {
                return ResourceManager.GetString("ACTPluginStopError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add timers instead of restarting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AddMessageCheckBox {
            get {
                return ResourceManager.GetString("AddMessageCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alarm and TTS과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AlarmTab {
            get {
                return ResourceManager.GetString("AlarmTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alchemist과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ALC {
            get {
                return ResourceManager.GetString("ALC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All Off과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AllOffButton {
            get {
                return ResourceManager.GetString("AllOffButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All On과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AllOnButton {
            get {
                return ResourceManager.GetString("AllOnButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テロップを常に表示する과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AlwaysDisplayTelop {
            get {
                return ResourceManager.GetString("AlwaysDisplayTelop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Analyze과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AnalyzeCombat {
            get {
                return ResourceManager.GetString("AnalyzeCombat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Apply과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ApplyButton {
            get {
                return ResourceManager.GetString("ApplyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Archer과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ARC {
            get {
                return ResourceManager.GetString("ARC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Armorer과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ARM {
            get {
                return ResourceManager.GetString("ARM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Astrologian과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AST {
            get {
                return ResourceManager.GetString("AST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;AST&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ASTLabel {
            get {
                return ResourceManager.GetString("ASTLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reverse sorting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AutoSortReverseCheckbox {
            get {
                return ResourceManager.GetString("AutoSortReverseCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alpha channel of the background color과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BackgroundColorAlphaTitle {
            get {
                return ResourceManager.GetString("BackgroundColorAlphaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bar size과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BarSize {
            get {
                return ResourceManager.GetString("BarSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Black Mage과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BLM {
            get {
                return ResourceManager.GetString("BLM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;BLM&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BLMLabel {
            get {
                return ResourceManager.GetString("BLMLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Botanist과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BOT {
            get {
                return ResourceManager.GetString("BOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bard과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BRD {
            get {
                return ResourceManager.GetString("BRD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;BRD&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BRDLabel {
            get {
                return ResourceManager.GetString("BRDLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Blacksmith과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BSM {
            get {
                return ResourceManager.GetString("BSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Buffer size과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BufferSize {
            get {
                return ResourceManager.GetString("BufferSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Background alpha...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ChangeBackgroundAlpha {
            get {
                return ResourceManager.GetString("ChangeBackgroundAlpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Background color...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ChangeBackgroundColor {
            get {
                return ResourceManager.GetString("ChangeBackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bar color...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ChangeBarColor {
            get {
                return ResourceManager.GetString("ChangeBarColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bar outline color...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ChangeBarOutlineColor {
            get {
                return ResourceManager.GetString("ChangeBarOutlineColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right click to edit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ChangeByRightClicking {
            get {
                return ResourceManager.GetString("ChangeByRightClicking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Font...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ChangeFont {
            get {
                return ResourceManager.GetString("ChangeFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Font color...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ChangeFontColor {
            get {
                return ResourceManager.GetString("ChangeFontColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Font outline color...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ChangeFontOutlineColor {
            get {
                return ResourceManager.GetString("ChangeFontOutlineColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete All과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ClearAllButton {
            get {
                return ResourceManager.GetString("ClearAllButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Click-through과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ClickThrough {
            get {
                return ResourceManager.GetString("ClickThrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Conjurer과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CNJ {
            get {
                return ResourceManager.GetString("CNJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Combat Analyzer과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CombatAnalyzerTabTitle {
            get {
                return ResourceManager.GetString("CombatAnalyzerTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Analyzing the log...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CombatAnalyzing {
            get {
                return ResourceManager.GetString("CombatAnalyzing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable combat log analysis과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CombatLogEnabledCheckBox {
            get {
                return ResourceManager.GetString("CombatLogEnabledCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Comma &quot;,&quot; makes new line과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CommaLineBreakExplain {
            get {
                return ResourceManager.GetString("CommaLineBreakExplain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy log과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CopyLog {
            get {
                return ResourceManager.GetString("CopyLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy log details과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CopyLogDetail {
            get {
                return ResourceManager.GetString("CopyLogDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Carpenter과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CRP {
            get {
                return ResourceManager.GetString("CRP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Culinarian과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CUL {
            get {
                return ResourceManager.GetString("CUL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Play sound after delay과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DelayedSoundEffect {
            get {
                return ResourceManager.GetString("DelayedSoundEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Play sound when log matches, after N seconds과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DelayedSoundEffectAfterMatch {
            get {
                return ResourceManager.GetString("DelayedSoundEffectAfterMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Detect FC:PacketDump과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DetectPacketDumpLabel {
            get {
                return ResourceManager.GetString("DetectPacketDumpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ※ Disabled when set to 0 (never hides)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DisableWhenClear {
            get {
                return ResourceManager.GetString("DisableWhenClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Priority과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DisplayOrderLabel {
            get {
                return ResourceManager.GetString("DisplayOrderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display progress bar과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DisplayRemainingTimeCheckBox {
            get {
                return ResourceManager.GetString("DisplayRemainingTimeCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   seconds과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DisplaySeconds {
            get {
                return ResourceManager.GetString("DisplaySeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Always show (even when completed)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DontHideCheckBox {
            get {
                return ResourceManager.GetString("DontHideCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to download?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DownloadPrompt {
            get {
                return ResourceManager.GetString("DownloadPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DQX向け機能を有効にする과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DQXOptionEnabledCheckBox {
            get {
                return ResourceManager.GetString("DQXOptionEnabledCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Option for DQX과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DQXOptionTabPage {
            get {
                return ResourceManager.GetString("DQXOptionTabPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;me&gt; : Player과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DQXPlayerNameLabel {
            get {
                return ResourceManager.GetString("DQXPlayerNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;2&gt; : Member2과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DQXPTMember2Label {
            get {
                return ResourceManager.GetString("DQXPTMember2Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;3&gt; : Member3과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DQXPTMember3Label {
            get {
                return ResourceManager.GetString("DQXPTMember3Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;4&gt; : Member4과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DQXPTMember4Label {
            get {
                return ResourceManager.GetString("DQXPTMember4Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;5&gt; : Member5과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DQXPTMember5Label {
            get {
                return ResourceManager.GetString("DQXPTMember5Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;6&gt; : Member6과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DQXPTMember6Label {
            get {
                return ResourceManager.GetString("DQXPTMember6Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;7&gt; : Member7과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DQXPTMember7Label {
            get {
                return ResourceManager.GetString("DQXPTMember7Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;8&gt; : Member8과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DQXPTMember8Label {
            get {
                return ResourceManager.GetString("DQXPTMember8Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dragoon과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DRG {
            get {
                return ResourceManager.GetString("DRG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;DRG&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DRGLabel {
            get {
                return ResourceManager.GetString("DRGLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dark Knight과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DRK {
            get {
                return ResourceManager.GetString("DRK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;DRK&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DRKLabel {
            get {
                return ResourceManager.GetString("DRKLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Duration과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Elapsed seconds과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ElapsedHeader {
            get {
                return ResourceManager.GetString("ElapsedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enabled과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enabled과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string EnabledSpellTimerNoDecimalCheckBox {
            get {
                return ResourceManager.GetString("EnabledSpellTimerNoDecimalCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hide spell timers after completion과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string EraseAfterRecast {
            get {
                return ResourceManager.GetString("EraseAfterRecast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ExportButton {
            get {
                return ResourceManager.GetString("ExportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ExportCSVButton {
            get {
                return ResourceManager.GetString("ExportCSVButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extend beyond the original recast time과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ExtendBeyondOriginalRecastTimeCheckBox {
            get {
                return ResourceManager.GetString("ExtendBeyondOriginalRecastTimeCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Upper limit of the extension (in seconds)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ExtendLimitLabel {
            get {
                return ResourceManager.GetString("ExtendLimitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fix spell position과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FixedPositionSpell {
            get {
                return ResourceManager.GetString("FixedPositionSpell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fisher과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FSH {
            get {
                return ResourceManager.GetString("FSH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   General과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GeneralTab {
            get {
                return ResourceManager.GetString("GeneralTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gladiator과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GLD {
            get {
                return ResourceManager.GetString("GLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Goldsmith과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GSM {
            get {
                return ResourceManager.GetString("GSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hide Spell Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HideSpellNameCheckBox {
            get {
                return ResourceManager.GetString("HideSpellNameCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hide  overlays when inactive.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HideWhenNotActiceCheckBox {
            get {
                return ResourceManager.GetString("HideWhenNotActiceCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Horizontal Layout과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HorizontalLayout {
            get {
                return ResourceManager.GetString("HorizontalLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HP과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HPHeader {
            get {
                return ResourceManager.GetString("HPHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Play sound when log matches과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ImmediateSoundEffect {
            get {
                return ResourceManager.GetString("ImmediateSoundEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ImportButton {
            get {
                return ResourceManager.GetString("ImportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset to defaults과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InitializationButton {
            get {
                return ResourceManager.GetString("InitializationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Is Running과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string IsRunning {
            get {
                return ResourceManager.GetString("IsRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Is Stopping과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string IsStopping {
            get {
                return ResourceManager.GetString("IsStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language (言語)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Combat Log Analyze과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string lblCombatAnalyzer {
            get {
                return ResourceManager.GetString("lblCombatAnalyzer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Party Member Alarm과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string lblDQX {
            get {
                return ResourceManager.GetString("lblDQX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language Setting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string lblLanguage {
            get {
                return ResourceManager.GetString("lblLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Monitor과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string lblMonitor {
            get {
                return ResourceManager.GetString("lblMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Spell Timer Setting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string lblSpellTimer {
            get {
                return ResourceManager.GetString("lblSpellTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   lines과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LinesLabel {
            get {
                return ResourceManager.GetString("LinesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Special SpellTimer (SupeSupe)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LN_Tabname {
            get {
                return ResourceManager.GetString("LN_Tabname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lancer과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LNC {
            get {
                return ResourceManager.GetString("LNC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load color scheme과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LoadColorSet {
            get {
                return ResourceManager.GetString("LoadColorSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An exception occurred by a load of a XML file.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LoadXMLError {
            get {
                return ResourceManager.GetString("LoadXMLError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Location과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Log과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LogHeader {
            get {
                return ResourceManager.GetString("LogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Log과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LogLabel {
            get {
                return ResourceManager.GetString("LogLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Log poll sleep interval과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LogPollSleepIntervalLabel {
            get {
                return ResourceManager.GetString("LogPollSleepIntervalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Log과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LogTabPage {
            get {
                return ResourceManager.GetString("LogTabPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LogTypeHeader {
            get {
                return ResourceManager.GetString("LogTypeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Leatherworker과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LTW {
            get {
                return ResourceManager.GetString("LTW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Margin과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Margin {
            get {
                return ResourceManager.GetString("Margin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This looks for partial matches in the game log\nExample)\r\nIf you chose &quot;freezing sword&quot; as your matching text.\nAnd the log contains the string &quot;Shiva uses stance of freezing sword&quot;.\n→ Then this would match that line in the game log.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MatchingKeywordExplanationTooltip {
            get {
                return ResourceManager.GetString("MatchingKeywordExplanationTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Matching log text to show과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MatchingLogWordLabel {
            get {
                return ResourceManager.GetString("MatchingLogWordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Matching log text for extending과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MatchingLogWordToExpandLabel {
            get {
                return ResourceManager.GetString("MatchingLogWordToExpandLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Matching log text to hide과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MatchingWordsToHide {
            get {
                return ResourceManager.GetString("MatchingWordsToHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delay before displaying과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MatchLogLabel {
            get {
                return ResourceManager.GetString("MatchLogLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Machinist과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MCH {
            get {
                return ResourceManager.GetString("MCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;MCH&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MCHLabel {
            get {
                return ResourceManager.GetString("MCHLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;me&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MeLabel {
            get {
                return ResourceManager.GetString("MeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;2&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Member2Label {
            get {
                return ResourceManager.GetString("Member2Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;3&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Member3Label {
            get {
                return ResourceManager.GetString("Member3Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;4&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Member4Label {
            get {
                return ResourceManager.GetString("Member4Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;5&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Member5Label {
            get {
                return ResourceManager.GetString("Member5Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;6&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Member6Label {
            get {
                return ResourceManager.GetString("Member6Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;7&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Member7Label {
            get {
                return ResourceManager.GetString("Member7Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;8&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Member8Label {
            get {
                return ResourceManager.GetString("Member8Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Message to display on ticker과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MessageOnTickerLabel {
            get {
                return ResourceManager.GetString("MessageOnTickerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Millisecs과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Millisecond {
            get {
                return ResourceManager.GetString("Millisecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Miner과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MIN {
            get {
                return ResourceManager.GetString("MIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Monk과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MNK {
            get {
                return ResourceManager.GetString("MNK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;MNK&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MNKLabel {
            get {
                return ResourceManager.GetString("MNKLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Monitor과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MonitorTabPage {
            get {
                return ResourceManager.GetString("MonitorTabPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Marauder과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MRD {
            get {
                return ResourceManager.GetString("MRD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Telop과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NewTelop {
            get {
                return ResourceManager.GetString("NewTelop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An exception occurred in the confirmation of updates: {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NewVersionError {
            get {
                return ResourceManager.GetString("NewVersionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New version of {0} has been released.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NewVersionReleased {
            get {
                return ResourceManager.GetString("NewVersionReleased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ninja과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NIN {
            get {
                return ResourceManager.GetString("NIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;NIN&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NINLabel {
            get {
                return ResourceManager.GetString("NINLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string No1Label {
            get {
                return ResourceManager.GetString("No1Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string No2Label {
            get {
                return ResourceManager.GetString("No2Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ※ Notify ACT&apos;s SpellTimer when log matched. (Experimental)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NotifyNormalSpellTimerExplainLabel {
            get {
                return ResourceManager.GetString("NotifyNormalSpellTimerExplainLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Notify ACT&apos;s SpellTimer과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NotifyNormalSpellTimerLabel {
            get {
                return ResourceManager.GetString("NotifyNormalSpellTimerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NumberHeader {
            get {
                return ResourceManager.GetString("NumberHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OKButton {
            get {
                return ResourceManager.GetString("OKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   0: Transparent, 255: Opaque과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OpacityDescription {
            get {
                return ResourceManager.GetString("OpacityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Options과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OptionTabPageTitle {
            get {
                return ResourceManager.GetString("OptionTabPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Overlap Recast Time과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OverlapRecastTimeCheckBox {
            get {
                return ResourceManager.GetString("OverlapRecastTimeCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display overlay: OFF과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OverlayDisplaySwitchIsOff {
            get {
                return ResourceManager.GetString("OverlayDisplaySwitchIsOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display overlay: ON과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OverlayDisplaySwitchIsOn {
            get {
                return ResourceManager.GetString("OverlayDisplaySwitchIsOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display overlay even if FFXIV is not running과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OverlayForceVisibleCheckBox {
            get {
                return ResourceManager.GetString("OverlayForceVisibleCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Text to display when the timer is complete (Over)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OverTextLabel {
            get {
                return ResourceManager.GetString("OverTextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Panel name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PanelNameLabel {
            get {
                return ResourceManager.GetString("PanelNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ※ &lt;2&gt; - &lt;8&gt; can be used, however the order may be incorrect.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PartyMemberNumberExplainLabel {
            get {
                return ResourceManager.GetString("PartyMemberNumberExplainLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use party member names in matching과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PartyPronounLabel {
            get {
                return ResourceManager.GetString("PartyPronounLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ♪과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PlayButton {
            get {
                return ResourceManager.GetString("PlayButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Paladin과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PLD {
            get {
                return ResourceManager.GetString("PLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;PLD&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PLDLabel {
            get {
                return ResourceManager.GetString("PLDLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please Wait과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PleaseWait1 {
            get {
                return ResourceManager.GetString("PleaseWait1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please Wait .과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PleaseWait2 {
            get {
                return ResourceManager.GetString("PleaseWait2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please Wait . .과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PleaseWait3 {
            get {
                return ResourceManager.GetString("PleaseWait3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please Wait . . .과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PleaseWait4 {
            get {
                return ResourceManager.GetString("PleaseWait4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please Wait . . . .과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PleaseWait5 {
            get {
                return ResourceManager.GetString("PleaseWait5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ※ Smaller has more priority과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PriorityExplainLabel {
            get {
                return ResourceManager.GetString("PriorityExplainLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Progress bar appearance과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ProgressBarAppearance {
            get {
                return ResourceManager.GetString("ProgressBarAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pugilist과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PUG {
            get {
                return ResourceManager.GetString("PUG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Text to display when the timer is complete (Ready)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReadyTextLabel {
            get {
                return ResourceManager.GetString("ReadyTextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Play sound when timer expires과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RecastCompleteSoundEffect {
            get {
                return ResourceManager.GetString("RecastCompleteSoundEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recast time (seconds)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RecastTimeLabel {
            get {
                return ResourceManager.GetString("RecastTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   During the recast time reduce brightness of icon과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReduceIconBrightness {
            get {
                return ResourceManager.GetString("ReduceIconBrightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   During the recast time reduce brightness of icon과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReduceIconBrightnessCheckBox {
            get {
                return ResourceManager.GetString("ReduceIconBrightnessCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReferenceButton {
            get {
                return ResourceManager.GetString("ReferenceButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Regular expression matching is disabled by default.\nPrefer partial string matching instead of regular expressions for better performance.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RegularExpressionExplanationTooltip {
            get {
                return ResourceManager.GetString("RegularExpressionExplanationTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   To remove Tooltip symbols.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RemoveTooltipSymbolsLabel {
            get {
                return ResourceManager.GetString("RemoveTooltipSymbolsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Repeat과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RepeatCheckBox {
            get {
                return ResourceManager.GetString("RepeatCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ※ Requires restart과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RequiresRestart {
            get {
                return ResourceManager.GetString("RequiresRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to reset all settings and ticker positions?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ResetAllPrompt {
            get {
                return ResourceManager.GetString("ResetAllPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset counter at wipe out.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ResetOnWipeOutLabel {
            get {
                return ResourceManager.GetString("ResetOnWipeOutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Apply bar size to all spell timers과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ResetSpellBarSize {
            get {
                return ResourceManager.GetString("ResetSpellBarSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Apply colors to all spell timers과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ResetSpellColor {
            get {
                return ResourceManager.GetString("ResetSpellColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Apply font to all spell timers과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ResetSpellFont {
            get {
                return ResourceManager.GetString("ResetSpellFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Apply color to all tickers과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ResetTelopColor {
            get {
                return ResourceManager.GetString("ResetTelopColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Apply font to all tickers과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ResetTelopFont {
            get {
                return ResourceManager.GetString("ResetTelopFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reverse direciton과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReverseDirectionCheckbox {
            get {
                return ResourceManager.GetString("ReverseDirectionCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rogue과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ROG {
            get {
                return ResourceManager.GetString("ROG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sample spell과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SampleSpell {
            get {
                return ResourceManager.GetString("SampleSpell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sample ticker과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SampleTelop {
            get {
                return ResourceManager.GetString("SampleTelop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save color scheme과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SaveColorSet {
            get {
                return ResourceManager.GetString("SaveColorSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save the log.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SaveLogLabel {
            get {
                return ResourceManager.GetString("SaveLogLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scholar과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SCH {
            get {
                return ResourceManager.GetString("SCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;SCH&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SCHLabel {
            get {
                return ResourceManager.GetString("SCHLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Screen update interval과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ScreenUpdateTimeLabel {
            get {
                return ResourceManager.GetString("ScreenUpdateTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Seconds과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SecondsLabel {
            get {
                return ResourceManager.GetString("SecondsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Seconds later과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SecondsLater {
            get {
                return ResourceManager.GetString("SecondsLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select all과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Job Filter...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SelectJobButton {
            get {
                return ResourceManager.GetString("SelectJobButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ※ If you want to limit the job of interest, please turn ON the check과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SelectJobSubtitle {
            get {
                return ResourceManager.GetString("SelectJobSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select the job of interest과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SelectJobTitle {
            get {
                return ResourceManager.GetString("SelectJobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zone Filter...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SelectZoneButton {
            get {
                return ResourceManager.GetString("SelectZoneButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select zones과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SelectZoneTitle {
            get {
                return ResourceManager.GetString("SelectZoneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Conditions for Start...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SetConditionForStartButton {
            get {
                return ResourceManager.GetString("SetConditionForStartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select conditions과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SetConditionTitle {
            get {
                return ResourceManager.GetString("SetConditionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set time zero to here과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SetLogOrigin {
            get {
                return ResourceManager.GetString("SetLogOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show visual timer and progress bar과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ShowProgressBarCheckBox {
            get {
                return ResourceManager.GetString("ShowProgressBarCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   To simplify the Regex.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SimpleRegexLabel {
            get {
                return ResourceManager.GetString("SimpleRegexLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Summoner과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SMN {
            get {
                return ResourceManager.GetString("SMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;SMN&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SMNLabel {
            get {
                return ResourceManager.GetString("SMNLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sort spell timers by next recast과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SortByRecastOrder {
            get {
                return ResourceManager.GetString("SortByRecastOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Play sound before complete, before N seconds과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SoundEffectBeforeComplete {
            get {
                return ResourceManager.GetString("SoundEffectBeforeComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An exception occurred in the regeneration of ACT.SpecialSpellTimer Sound.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SoundError {
            get {
                return ResourceManager.GetString("SoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delay until sound plays (in seconds)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SoundInSeconds {
            get {
                return ResourceManager.GetString("SoundInSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Before seconds과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SoundInSecondsBefore {
            get {
                return ResourceManager.GetString("SoundInSecondsBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Period과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SpanHeader {
            get {
                return ResourceManager.GetString("SpanHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ▶과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SpeakButton {
            get {
                return ResourceManager.GetString("SpeakButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ※ Please set according to your machine specs.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SpecsLabel {
            get {
                return ResourceManager.GetString("SpecsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to delete all spell timers?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SpellClearAllPrompt {
            get {
                return ResourceManager.GetString("SpellClearAllPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Spell Icon과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SpellIconLabel {
            get {
                return ResourceManager.GetString("SpellIconLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Size of Spell Icon과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SpellIconSizeLabel {
            get {
                return ResourceManager.GetString("SpellIconSizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Spell name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SpellNameLabel {
            get {
                return ResourceManager.GetString("SpellNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ※ A performance of drawing improves. (Requires restart)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SpellTimerFormatExplainLabel {
            get {
                return ResourceManager.GetString("SpellTimerFormatExplainLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recast time of spell timers is indicated by an integer.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SpellTimerFormatLabel {
            get {
                return ResourceManager.GetString("SpellTimerFormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An exception occurred in the Refresh of ACT.SpecialSpellTimer spell timer Window.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SpellTimerRefreshError {
            get {
                return ResourceManager.GetString("SpellTimerRefreshError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Spell Timers과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SpellTimerTabTitle {
            get {
                return ResourceManager.GetString("SpellTimerTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SupeSupe과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SupeSupe {
            get {
                return ResourceManager.GetString("SupeSupe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display spell과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SwitchOverlayButton {
            get {
                return ResourceManager.GetString("SwitchOverlayButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Detail Options과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string tabDetailOptions {
            get {
                return ResourceManager.GetString("tabDetailOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Overlay Options과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string tabOverlayOptions {
            get {
                return ResourceManager.GetString("tabOverlayOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add New과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TelopAddButton {
            get {
                return ResourceManager.GetString("TelopAddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear All과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TelopClearAllButton {
            get {
                return ResourceManager.GetString("TelopClearAllButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to delete all tickers?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TelopClearAllPrompt {
            get {
                return ResourceManager.GetString("TelopClearAllPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display all tickers\n(for position adjustment): OFF과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TelopDisplaySwitchIsOff {
            get {
                return ResourceManager.GetString("TelopDisplaySwitchIsOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display all tickers\n(for position adjustment): ON과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TelopDisplaySwitchIsOn {
            get {
                return ResourceManager.GetString("TelopDisplaySwitchIsOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TelopExportButton {
            get {
                return ResourceManager.GetString("TelopExportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TelopImportButton {
            get {
                return ResourceManager.GetString("TelopImportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   For the displayed message, {COUNT} will be replaced by the number of seconds until the ticker completes.\n{COUNT} → displays a single decimal point (eg. 30.0)\n{COUNT0} → display no decimals (eg. 30)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TelopMessageExplanationTooltip {
            get {
                return ResourceManager.GetString("TelopMessageExplanationTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tickers과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TelopTabPageTitle {
            get {
                return ResourceManager.GetString("TelopTabPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Text to speak과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TextToSpeakLabel {
            get {
                return ResourceManager.GetString("TextToSpeakLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Thaumaturge과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string THM {
            get {
                return ResourceManager.GetString("THM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ticker name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TickerName {
            get {
                return ResourceManager.GetString("TickerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Timestamp과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TimestampHeader {
            get {
                return ResourceManager.GetString("TimestampHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   When being different in a spell name (indication text), I become an instance.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ToInstanceCheckBox {
            get {
                return ResourceManager.GetString("ToInstanceCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Overlay opacity과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TransmitOverlay {
            get {
                return ResourceManager.GetString("TransmitOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UpdateButton {
            get {
                return ResourceManager.GetString("UpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter the spell name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UpdateSpellNameTitle {
            get {
                return ResourceManager.GetString("UpdateSpellNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter the panel name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UpdateSpellPanelTitle {
            get {
                return ResourceManager.GetString("UpdateSpellPanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter the name of the ticker과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UpdateTelopNameTitle {
            get {
                return ResourceManager.GetString("UpdateTelopNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use other than FFXIV.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UseOtherThanFFXIVCheckbox {
            get {
                return ResourceManager.GetString("UseOtherThanFFXIVCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use Regex과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UseRegex {
            get {
                return ResourceManager.GetString("UseRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warrior과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WAR {
            get {
                return ResourceManager.GetString("WAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;WAR&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WARLabel {
            get {
                return ResourceManager.GetString("WARLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An exception occurred in the Watch foreground window.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WatchActiveError {
            get {
                return ResourceManager.GetString("WatchActiveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sound effect과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WaveSoundLabel {
            get {
                return ResourceManager.GetString("WaveSoundLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   White Mage과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WHM {
            get {
                return ResourceManager.GetString("WHM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;WHM&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WHMLabel {
            get {
                return ResourceManager.GetString("WHMLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Weaver과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WVR {
            get {
                return ResourceManager.GetString("WVR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   X과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string X {
            get {
                return ResourceManager.GetString("X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XML files (*.xml)|*.xml|All files (*.*)|*.*과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string XmlFileFilter {
            get {
                return ResourceManager.GetString("XmlFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Y과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Y {
            get {
                return ResourceManager.GetString("Y", resourceCulture);
            }
        }
    }
}
